// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../../core/models/entity/app_data.dart';
import '../../../core/models/entity/app_setting_entity.dart';
import '../../../core/models/entity/developer_mode_entity.dart';
import '../../../core/models/entity/plan_entity.dart';
import '../../../core/models/entity/private_server_entity.dart';
import '../../../core/models/entity/server_location_entity.dart';
import '../../../core/models/entity/user_entity.dart';
import '../../../core/models/entity/website.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8109438054083727979),
    name: 'AppData',
    lastPropertyId: const obx_int.IdUid(9, 6529008235197556438),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5818484395233506486),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4692644670620420896),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8095874281193740959),
        name: 'bundleId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 251056091016684547),
        name: 'iconBytes',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2495380619769283149),
        name: 'iconPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4450097850864964786),
        name: 'appPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 961998165971833378),
        name: 'isEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3070023067299481568),
        name: 'lastUpdateTime',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6529008235197556438),
        name: 'removed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 687217704776011576),
    name: 'AppSetting',
    lastPropertyId: const obx_int.IdUid(16, 4485043618273916447),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3510248969077851513),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9205281046748929972),
        name: 'isPro',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3039149514872679626),
        name: 'isSplitTunnelingOn',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8380353672446932820),
        name: 'locale',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2654649825181931771),
        name: 'oAuthToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6744815296056712828),
        name: 'userLoggedIn',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7437540425271471596),
        name: 'blockAds',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2584154697741095523),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4176228116314272090),
        name: 'showSplashScreen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8918901309223826671),
        name: 'telemetryConsent',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2408270352417603228),
        name: 'telemetryDialogDismissed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 2605651149110192739),
        name: 'successfulConnection',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 4485043618273916447),
        name: 'routingMode',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4249170330039132700),
    name: 'DeviceEntity',
    lastPropertyId: const obx_int.IdUid(4, 4534248771562227303),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6219343342665160538),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4315712206534823632),
        name: 'deviceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8612932721577961741),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4534248771562227303),
        name: 'created',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3560385032646551002),
    name: 'PlanEntity',
    lastPropertyId: const obx_int.IdUid(7, 6158226158904339406),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2720786197251840219),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8958483070134897826),
        name: 'planId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4745648735026846740),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4334998974030680973),
        name: 'usdPrice',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7124565832351714757),
        name: 'priceJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 92192598281512897),
        name: 'expectedMonthlyPriceJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6158226158904339406),
        name: 'bestValue',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6788300525743464189),
    name: 'PlansDataEntity',
    lastPropertyId: const obx_int.IdUid(2, 1177257349040850931),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4903918207916946738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1177257349040850931),
        name: 'providersId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3698291161957906507),
        relationTarget: 'ProvidersEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8469458207073317900),
        name: 'plans',
        targetId: const obx_int.IdUid(4, 3560385032646551002),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 4973796228302910111),
    name: 'PrivateServerEntity',
    lastPropertyId: const obx_int.IdUid(11, 5980712756656597442),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8851495684939286531),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7849498949423812270),
        name: 'serverName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 887911796261161710),
        name: 'externalIp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6797091314608446454),
        name: 'port',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6240428073828203383),
        name: 'accessToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4385552681893466490),
        name: 'isJoined',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1698964234609177040),
        name: 'userSelected',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8094537589605119730),
        name: 'serverLocationName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2586080786978004288),
        name: 'serverCountryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5980712756656597442),
        name: 'protocol',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 6691597768245889915),
    name: 'ProvidersEntity',
    lastPropertyId: const obx_int.IdUid(3, 5935241594084587109),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5517050892681061779),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 279451116197837791),
        name: 'androidJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5935241594084587109),
        name: 'desktopJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5545500259183948018),
    name: 'PurchaseEntity',
    lastPropertyId: const obx_int.IdUid(2, 8572914888166586456),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4224063114469865839),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8572914888166586456),
        name: 'plan',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 1096450388891752501),
    name: 'SubscriptionDataEntity',
    lastPropertyId: const obx_int.IdUid(11, 1039889632731608866),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8350585657529793815),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2437269426733701891),
        name: 'planID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2822712554306251226),
        name: 'stripeCustomerID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8459180929304848498),
        name: 'startAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6124200714268672074),
        name: 'cancelledAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 785942654616011781),
        name: 'autoRenew',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 154235044404873355),
        name: 'subscriptionID',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7093310064649865460),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7082703063040117060),
        name: 'provider',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3514898942296912508),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1039889632731608866),
        name: 'endAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 4557824412096950738),
    name: 'UserDataEntity',
    lastPropertyId: const obx_int.IdUid(21, 6487851609758792533),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3520340269568541650),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8888824583143494434),
        name: 'userId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5865459003418072795),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 575650820145266208),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7905659079402253505),
        name: 'referral',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1307967724187900608),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1402080787246041136),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8674297678038990158),
        name: 'userStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3814725059768601103),
        name: 'userLevel',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1457534506886623999),
        name: 'locale',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 89054036995768249),
        name: 'expiration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3632977673947554173),
        name: 'subscription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6824989649522459733),
        name: 'bonusDays',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7346983348387844755),
        name: 'bonusMonths',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1734428572922835814),
        name: 'yinbiEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8393843414357574519),
        name: 'servers',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5415899482391977201),
        name: 'inviters',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3655044443993528317),
        name: 'invitees',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 7458790967605749096),
        name: 'purchases',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 1498461655287117981),
        name: 'subscriptionDataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 3153991439170111111),
        relationTarget: 'SubscriptionDataEntity',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 6487851609758792533),
        name: 'deviceID',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 297124301285732315),
        name: 'devices',
        targetId: const obx_int.IdUid(3, 4249170330039132700),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 246288270905950306),
    name: 'UserResponseEntity',
    lastPropertyId: const obx_int.IdUid(6, 7755562986946953188),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8953156686709270278),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8750795235920520422),
        name: 'legacyID',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 476511431574864213),
        name: 'legacyToken',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8252409828556421464),
        name: 'emailConfirmed',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5056325535516113749),
        name: 'success',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7755562986946953188),
        name: 'legacyUserDataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 1452151582306513699),
        relationTarget: 'UserDataEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 5180174885065282242),
        name: 'devices',
        targetId: const obx_int.IdUid(3, 4249170330039132700),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(13, 5371815775673175384),
    name: 'Website',
    lastPropertyId: const obx_int.IdUid(2, 6278046723197261570),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7537711909627555199),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6278046723197261570),
        name: 'domain',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(15, 8199208392537907961),
    name: 'ServerLocationEntity',
    lastPropertyId: const obx_int.IdUid(11, 4150978985643450510),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5986838658829785528),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8032330847275345473),
        name: 'serverName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 616996754378264721),
        name: 'serverType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 9033661669185195868),
        name: 'countryCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2125473202380216965),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 9004572906869766608),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7845913040190483495),
        name: 'displayName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8116798153105246070),
        name: 'autoLocationJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4150978985643450510),
        name: 'protocol',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(16, 7100413957344193553),
    name: 'DeveloperModeEntity',
    lastPropertyId: const obx_int.IdUid(3, 7373006372417925915),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2238654845681546490),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7656944821432278757),
        name: 'testPlayPurchaseEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7373006372417925915),
        name: 'testStripePurchaseEnabled',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(16, 7100413957344193553),
    lastIndexId: const obx_int.IdUid(3, 1452151582306513699),
    lastRelationId: const obx_int.IdUid(3, 5180174885065282242),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2570208090016598017, 893519286503285129],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4825495648663424466,
      1950518450967111905,
      6118839343664935194,
      6466241492119077741,
      2440100772065290852,
      2624216199337903862,
      713889304334787730,
      2938245810653001410,
      3575184890349121426,
      7033573124845738437,
      8638115978305760525,
      2297478623142907793,
      8153428725932858000,
      6825758662513353714,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppData: obx_int.EntityDefinition<AppData>(
      model: _entities[0],
      toOneRelations: (AppData object) => [],
      toManyRelations: (AppData object) => {},
      getId: (AppData object) => object.id,
      setId: (AppData object, int id) {
        object.id = id;
      },
      objectToFB: (AppData object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final bundleIdOffset = fbb.writeString(object.bundleId);
        final iconBytesOffset = object.iconBytes == null
            ? null
            : fbb.writeListInt8(object.iconBytes!);
        final iconPathOffset = fbb.writeString(object.iconPath);
        final appPathOffset = fbb.writeString(object.appPath);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, bundleIdOffset);
        fbb.addOffset(3, iconBytesOffset);
        fbb.addOffset(4, iconPathOffset);
        fbb.addOffset(5, appPathOffset);
        fbb.addBool(6, object.isEnabled);
        fbb.addInt64(7, object.lastUpdateTime);
        fbb.addBool(8, object.removed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bundleIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final iconBytesParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGetNullable(buffer, rootOffset, 10)
                as Uint8List?;
        final iconPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final appPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final isEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final lastUpdateTimeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final removedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object = AppData(
          id: idParam,
          name: nameParam,
          bundleId: bundleIdParam,
          iconBytes: iconBytesParam,
          iconPath: iconPathParam,
          appPath: appPathParam,
          isEnabled: isEnabledParam,
          lastUpdateTime: lastUpdateTimeParam,
          removed: removedParam,
        );

        return object;
      },
    ),
    AppSetting: obx_int.EntityDefinition<AppSetting>(
      model: _entities[1],
      toOneRelations: (AppSetting object) => [],
      toManyRelations: (AppSetting object) => {},
      getId: (AppSetting object) => object.id,
      setId: (AppSetting object, int id) {
        object.id = id;
      },
      objectToFB: (AppSetting object, fb.Builder fbb) {
        final localeOffset = fbb.writeString(object.locale);
        final oAuthTokenOffset = fbb.writeString(object.oAuthToken);
        final emailOffset = fbb.writeString(object.email);
        final routingModeOffset = fbb.writeString(object.routingMode);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.isPro);
        fbb.addBool(2, object.isSplitTunnelingOn);
        fbb.addOffset(3, localeOffset);
        fbb.addOffset(4, oAuthTokenOffset);
        fbb.addBool(5, object.userLoggedIn);
        fbb.addBool(6, object.blockAds);
        fbb.addOffset(7, emailOffset);
        fbb.addBool(8, object.showSplashScreen);
        fbb.addBool(12, object.telemetryConsent);
        fbb.addBool(13, object.telemetryDialogDismissed);
        fbb.addBool(14, object.successfulConnection);
        fbb.addOffset(15, routingModeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final isProParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final isSplitTunnelingOnParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final userLoggedInParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final oAuthTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final blockAdsParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final localeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final showSplashScreenParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final telemetryDialogDismissedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final telemetryConsentParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          28,
          false,
        );
        final successfulConnectionParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final routingModeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final object = AppSetting(
          id: idParam,
          isPro: isProParam,
          isSplitTunnelingOn: isSplitTunnelingOnParam,
          userLoggedIn: userLoggedInParam,
          oAuthToken: oAuthTokenParam,
          blockAds: blockAdsParam,
          email: emailParam,
          locale: localeParam,
          showSplashScreen: showSplashScreenParam,
          telemetryDialogDismissed: telemetryDialogDismissedParam,
          telemetryConsent: telemetryConsentParam,
          successfulConnection: successfulConnectionParam,
          routingMode: routingModeParam,
        );

        return object;
      },
    ),
    DeviceEntity: obx_int.EntityDefinition<DeviceEntity>(
      model: _entities[2],
      toOneRelations: (DeviceEntity object) => [],
      toManyRelations: (DeviceEntity object) => {},
      getId: (DeviceEntity object) => object.id,
      setId: (DeviceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DeviceEntity object, fb.Builder fbb) {
        final deviceIdOffset = fbb.writeString(object.deviceId);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, deviceIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.created);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final deviceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final createdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = DeviceEntity(
          id: idParam,
          deviceId: deviceIdParam,
          name: nameParam,
          created: createdParam,
        );

        return object;
      },
    ),
    PlanEntity: obx_int.EntityDefinition<PlanEntity>(
      model: _entities[3],
      toOneRelations: (PlanEntity object) => [],
      toManyRelations: (PlanEntity object) => {},
      getId: (PlanEntity object) => object.id,
      setId: (PlanEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlanEntity object, fb.Builder fbb) {
        final planIdOffset = fbb.writeString(object.planId);
        final descriptionOffset = fbb.writeString(object.description);
        final priceJsonOffset = fbb.writeString(object.priceJson);
        final expectedMonthlyPriceJsonOffset = fbb.writeString(
          object.expectedMonthlyPriceJson,
        );
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, planIdOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.usdPrice);
        fbb.addOffset(4, priceJsonOffset);
        fbb.addOffset(5, expectedMonthlyPriceJsonOffset);
        fbb.addBool(6, object.bestValue);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final planIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final usdPriceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final priceJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final expectedMonthlyPriceJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final bestValueParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final object = PlanEntity(
          planId: planIdParam,
          description: descriptionParam,
          usdPrice: usdPriceParam,
          priceJson: priceJsonParam,
          expectedMonthlyPriceJson: expectedMonthlyPriceJsonParam,
          bestValue: bestValueParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PlansDataEntity: obx_int.EntityDefinition<PlansDataEntity>(
      model: _entities[4],
      toOneRelations: (PlansDataEntity object) => [object.providers],
      toManyRelations: (PlansDataEntity object) => {
        obx_int.RelInfo<PlansDataEntity>.toMany(1, object.id): object.plans,
      },
      getId: (PlansDataEntity object) => object.id,
      setId: (PlansDataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlansDataEntity object, fb.Builder fbb) {
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.providers.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlansDataEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.providers.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.providers.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<PlansDataEntity>(
          object.plans,
          store,
          obx_int.RelInfo<PlansDataEntity>.toMany(1, object.id),
        );
        return object;
      },
    ),
    PrivateServerEntity: obx_int.EntityDefinition<PrivateServerEntity>(
      model: _entities[5],
      toOneRelations: (PrivateServerEntity object) => [],
      toManyRelations: (PrivateServerEntity object) => {},
      getId: (PrivateServerEntity object) => object.id,
      setId: (PrivateServerEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PrivateServerEntity object, fb.Builder fbb) {
        final serverNameOffset = fbb.writeString(object.serverName);
        final externalIpOffset = fbb.writeString(object.externalIp);
        final portOffset = fbb.writeString(object.port);
        final accessTokenOffset = fbb.writeString(object.accessToken);
        final serverLocationNameOffset = fbb.writeString(
          object.serverLocationName,
        );
        final serverCountryCodeOffset = fbb.writeString(
          object.serverCountryCode,
        );
        final protocolOffset = fbb.writeString(object.protocol);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, serverNameOffset);
        fbb.addOffset(2, externalIpOffset);
        fbb.addOffset(3, portOffset);
        fbb.addOffset(4, accessTokenOffset);
        fbb.addBool(6, object.isJoined);
        fbb.addBool(7, object.userSelected);
        fbb.addOffset(8, serverLocationNameOffset);
        fbb.addOffset(9, serverCountryCodeOffset);
        fbb.addOffset(10, protocolOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final serverNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final externalIpParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final portParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final accessTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final serverLocationNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final serverCountryCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final protocolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final isJoinedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final userSelectedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final object = PrivateServerEntity(
          serverName: serverNameParam,
          externalIp: externalIpParam,
          port: portParam,
          accessToken: accessTokenParam,
          serverLocationName: serverLocationNameParam,
          serverCountryCode: serverCountryCodeParam,
          protocol: protocolParam,
          isJoined: isJoinedParam,
          userSelected: userSelectedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ProvidersEntity: obx_int.EntityDefinition<ProvidersEntity>(
      model: _entities[6],
      toOneRelations: (ProvidersEntity object) => [],
      toManyRelations: (ProvidersEntity object) => {},
      getId: (ProvidersEntity object) => object.id,
      setId: (ProvidersEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProvidersEntity object, fb.Builder fbb) {
        final androidJsonOffset = fbb.writeString(object.androidJson);
        final desktopJsonOffset = fbb.writeString(object.desktopJson);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, androidJsonOffset);
        fbb.addOffset(2, desktopJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final androidJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final desktopJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ProvidersEntity(
          androidJson: androidJsonParam,
          desktopJson: desktopJsonParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    PurchaseEntity: obx_int.EntityDefinition<PurchaseEntity>(
      model: _entities[7],
      toOneRelations: (PurchaseEntity object) => [],
      toManyRelations: (PurchaseEntity object) => {},
      getId: (PurchaseEntity object) => object.id,
      setId: (PurchaseEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PurchaseEntity object, fb.Builder fbb) {
        final planOffset = fbb.writeString(object.plan);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, planOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final planParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PurchaseEntity(id: idParam, plan: planParam);

        return object;
      },
    ),
    SubscriptionDataEntity: obx_int.EntityDefinition<SubscriptionDataEntity>(
      model: _entities[8],
      toOneRelations: (SubscriptionDataEntity object) => [],
      toManyRelations: (SubscriptionDataEntity object) => {},
      getId: (SubscriptionDataEntity object) => object.id,
      setId: (SubscriptionDataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SubscriptionDataEntity object, fb.Builder fbb) {
        final planIDOffset = fbb.writeString(object.planID);
        final stripeCustomerIDOffset = fbb.writeString(object.stripeCustomerID);
        final startAtOffset = fbb.writeString(object.startAt);
        final cancelledAtOffset = fbb.writeString(object.cancelledAt);
        final subscriptionIDOffset = fbb.writeString(object.subscriptionID);
        final statusOffset = fbb.writeString(object.status);
        final providerOffset = fbb.writeString(object.provider);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final endAtOffset = fbb.writeString(object.endAt);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, planIDOffset);
        fbb.addOffset(2, stripeCustomerIDOffset);
        fbb.addOffset(3, startAtOffset);
        fbb.addOffset(4, cancelledAtOffset);
        fbb.addBool(5, object.autoRenew);
        fbb.addOffset(6, subscriptionIDOffset);
        fbb.addOffset(7, statusOffset);
        fbb.addOffset(8, providerOffset);
        fbb.addOffset(9, createdAtOffset);
        fbb.addOffset(10, endAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final planIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final stripeCustomerIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final startAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final cancelledAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final autoRenewParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final subscriptionIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final providerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final createdAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final endAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = SubscriptionDataEntity(
          id: idParam,
          planID: planIDParam,
          stripeCustomerID: stripeCustomerIDParam,
          startAt: startAtParam,
          cancelledAt: cancelledAtParam,
          autoRenew: autoRenewParam,
          subscriptionID: subscriptionIDParam,
          status: statusParam,
          provider: providerParam,
          createdAt: createdAtParam,
          endAt: endAtParam,
        );

        return object;
      },
    ),
    UserDataEntity: obx_int.EntityDefinition<UserDataEntity>(
      model: _entities[9],
      toOneRelations: (UserDataEntity object) => [object.subscriptionData],
      toManyRelations: (UserDataEntity object) => {
        obx_int.RelInfo<UserDataEntity>.toMany(2, object.id): object.devices,
      },
      getId: (UserDataEntity object) => object.id,
      setId: (UserDataEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserDataEntity object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        final tokenOffset = fbb.writeString(object.token);
        final referralOffset = fbb.writeString(object.referral);
        final phoneOffset = fbb.writeString(object.phone);
        final emailOffset = fbb.writeString(object.email);
        final userStatusOffset = fbb.writeString(object.userStatus);
        final userLevelOffset = fbb.writeString(object.userLevel);
        final localeOffset = fbb.writeString(object.locale);
        final subscriptionOffset = fbb.writeString(object.subscription);
        final bonusDaysOffset = fbb.writeString(object.bonusDays);
        final bonusMonthsOffset = fbb.writeString(object.bonusMonths);
        final serversOffset = fbb.writeString(object.servers);
        final invitersOffset = fbb.writeString(object.inviters);
        final inviteesOffset = fbb.writeString(object.invitees);
        final purchasesOffset = fbb.writeString(object.purchases);
        final deviceIDOffset = fbb.writeString(object.deviceID);
        fbb.startTable(22);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.userId);
        fbb.addOffset(2, codeOffset);
        fbb.addOffset(3, tokenOffset);
        fbb.addOffset(4, referralOffset);
        fbb.addOffset(5, phoneOffset);
        fbb.addOffset(6, emailOffset);
        fbb.addOffset(7, userStatusOffset);
        fbb.addOffset(8, userLevelOffset);
        fbb.addOffset(9, localeOffset);
        fbb.addInt64(10, object.expiration);
        fbb.addOffset(11, subscriptionOffset);
        fbb.addOffset(12, bonusDaysOffset);
        fbb.addOffset(13, bonusMonthsOffset);
        fbb.addBool(14, object.yinbiEnabled);
        fbb.addOffset(15, serversOffset);
        fbb.addOffset(16, invitersOffset);
        fbb.addOffset(17, inviteesOffset);
        fbb.addOffset(18, purchasesOffset);
        fbb.addInt64(19, object.subscriptionData.targetId);
        fbb.addOffset(20, deviceIDOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final userIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final tokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final referralParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final userStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final userLevelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final localeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final expirationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final subscriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final bonusDaysParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final bonusMonthsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final yinbiEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final serversParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 34, '');
        final invitersParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 36, '');
        final inviteesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final purchasesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 40, '');
        final deviceIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 44, '');
        final object = UserDataEntity(
          id: idParam,
          userId: userIdParam,
          code: codeParam,
          token: tokenParam,
          referral: referralParam,
          phone: phoneParam,
          email: emailParam,
          userStatus: userStatusParam,
          userLevel: userLevelParam,
          locale: localeParam,
          expiration: expirationParam,
          subscription: subscriptionParam,
          bonusDays: bonusDaysParam,
          bonusMonths: bonusMonthsParam,
          yinbiEnabled: yinbiEnabledParam,
          servers: serversParam,
          inviters: invitersParam,
          invitees: inviteesParam,
          purchases: purchasesParam,
          deviceID: deviceIDParam,
        );
        object.subscriptionData.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          42,
          0,
        );
        object.subscriptionData.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<UserDataEntity>(
          object.devices,
          store,
          obx_int.RelInfo<UserDataEntity>.toMany(2, object.id),
        );
        return object;
      },
    ),
    UserResponseEntity: obx_int.EntityDefinition<UserResponseEntity>(
      model: _entities[10],
      toOneRelations: (UserResponseEntity object) => [object.legacyUserData],
      toManyRelations: (UserResponseEntity object) => {
        obx_int.RelInfo<UserResponseEntity>.toMany(3, object.id):
            object.devices,
      },
      getId: (UserResponseEntity object) => object.id,
      setId: (UserResponseEntity object, int id) {
        object.id = id;
      },
      objectToFB: (UserResponseEntity object, fb.Builder fbb) {
        final legacyTokenOffset = fbb.writeString(object.legacyToken);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.legacyID);
        fbb.addOffset(2, legacyTokenOffset);
        fbb.addBool(3, object.emailConfirmed);
        fbb.addBool(4, object.success);
        fbb.addInt64(5, object.legacyUserData.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final legacyIDParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final legacyTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final emailConfirmedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final successParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          12,
          false,
        );
        final object = UserResponseEntity(
          id: idParam,
          legacyID: legacyIDParam,
          legacyToken: legacyTokenParam,
          emailConfirmed: emailConfirmedParam,
          success: successParam,
        );
        object.legacyUserData.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.legacyUserData.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<UserResponseEntity>(
          object.devices,
          store,
          obx_int.RelInfo<UserResponseEntity>.toMany(3, object.id),
        );
        return object;
      },
    ),
    Website: obx_int.EntityDefinition<Website>(
      model: _entities[11],
      toOneRelations: (Website object) => [],
      toManyRelations: (Website object) => {},
      getId: (Website object) => object.id,
      setId: (Website object, int id) {
        object.id = id;
      },
      objectToFB: (Website object, fb.Builder fbb) {
        final domainOffset = fbb.writeString(object.domain);
        fbb.startTable(3);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, domainOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final domainParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = Website(id: idParam, domain: domainParam);

        return object;
      },
    ),
    ServerLocationEntity: obx_int.EntityDefinition<ServerLocationEntity>(
      model: _entities[12],
      toOneRelations: (ServerLocationEntity object) => [],
      toManyRelations: (ServerLocationEntity object) => {},
      getId: (ServerLocationEntity object) => object.id,
      setId: (ServerLocationEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ServerLocationEntity object, fb.Builder fbb) {
        final serverNameOffset = fbb.writeString(object.serverName);
        final serverTypeOffset = fbb.writeString(object.serverType);
        final countryCodeOffset = fbb.writeString(object.countryCode);
        final countryOffset = fbb.writeString(object.country);
        final cityOffset = fbb.writeString(object.city);
        final displayNameOffset = fbb.writeString(object.displayName);
        final autoLocationJsonOffset = fbb.writeString(object.autoLocationJson);
        final protocolOffset = fbb.writeString(object.protocol);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(3, serverNameOffset);
        fbb.addOffset(4, serverTypeOffset);
        fbb.addOffset(5, countryCodeOffset);
        fbb.addOffset(6, countryOffset);
        fbb.addOffset(7, cityOffset);
        fbb.addOffset(8, displayNameOffset);
        fbb.addOffset(9, autoLocationJsonOffset);
        fbb.addOffset(10, protocolOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final serverNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final serverTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final protocolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final countryCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final displayNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final object =
            ServerLocationEntity(
                serverName: serverNameParam,
                serverType: serverTypeParam,
                protocol: protocolParam,
                countryCode: countryCodeParam,
                country: countryParam,
                city: cityParam,
                displayName: displayNameParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..autoLocationJson = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 22, '');

        return object;
      },
    ),
    DeveloperModeEntity: obx_int.EntityDefinition<DeveloperModeEntity>(
      model: _entities[13],
      toOneRelations: (DeveloperModeEntity object) => [],
      toManyRelations: (DeveloperModeEntity object) => {},
      getId: (DeveloperModeEntity object) => object.id,
      setId: (DeveloperModeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (DeveloperModeEntity object, fb.Builder fbb) {
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addBool(1, object.testPlayPurchaseEnabled);
        fbb.addBool(2, object.testStripePurchaseEnabled);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final testStripePurchaseEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final testPlayPurchaseEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final object = DeveloperModeEntity(
          testStripePurchaseEnabled: testStripePurchaseEnabledParam,
          testPlayPurchaseEnabled: testPlayPurchaseEnabledParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppData] entity fields to define ObjectBox queries.
class AppData_ {
  /// See [AppData.id].
  static final id = obx.QueryIntegerProperty<AppData>(
    _entities[0].properties[0],
  );

  /// See [AppData.name].
  static final name = obx.QueryStringProperty<AppData>(
    _entities[0].properties[1],
  );

  /// See [AppData.bundleId].
  static final bundleId = obx.QueryStringProperty<AppData>(
    _entities[0].properties[2],
  );

  /// See [AppData.iconBytes].
  static final iconBytes = obx.QueryByteVectorProperty<AppData>(
    _entities[0].properties[3],
  );

  /// See [AppData.iconPath].
  static final iconPath = obx.QueryStringProperty<AppData>(
    _entities[0].properties[4],
  );

  /// See [AppData.appPath].
  static final appPath = obx.QueryStringProperty<AppData>(
    _entities[0].properties[5],
  );

  /// See [AppData.isEnabled].
  static final isEnabled = obx.QueryBooleanProperty<AppData>(
    _entities[0].properties[6],
  );

  /// See [AppData.lastUpdateTime].
  static final lastUpdateTime = obx.QueryIntegerProperty<AppData>(
    _entities[0].properties[7],
  );

  /// See [AppData.removed].
  static final removed = obx.QueryBooleanProperty<AppData>(
    _entities[0].properties[8],
  );
}

/// [AppSetting] entity fields to define ObjectBox queries.
class AppSetting_ {
  /// See [AppSetting.id].
  static final id = obx.QueryIntegerProperty<AppSetting>(
    _entities[1].properties[0],
  );

  /// See [AppSetting.isPro].
  static final isPro = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[1],
  );

  /// See [AppSetting.isSplitTunnelingOn].
  static final isSplitTunnelingOn = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[2],
  );

  /// See [AppSetting.locale].
  static final locale = obx.QueryStringProperty<AppSetting>(
    _entities[1].properties[3],
  );

  /// See [AppSetting.oAuthToken].
  static final oAuthToken = obx.QueryStringProperty<AppSetting>(
    _entities[1].properties[4],
  );

  /// See [AppSetting.userLoggedIn].
  static final userLoggedIn = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[5],
  );

  /// See [AppSetting.blockAds].
  static final blockAds = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[6],
  );

  /// See [AppSetting.email].
  static final email = obx.QueryStringProperty<AppSetting>(
    _entities[1].properties[7],
  );

  /// See [AppSetting.showSplashScreen].
  static final showSplashScreen = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[8],
  );

  /// See [AppSetting.telemetryConsent].
  static final telemetryConsent = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[9],
  );

  /// See [AppSetting.telemetryDialogDismissed].
  static final telemetryDialogDismissed = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[10],
  );

  /// See [AppSetting.successfulConnection].
  static final successfulConnection = obx.QueryBooleanProperty<AppSetting>(
    _entities[1].properties[11],
  );

  /// See [AppSetting.routingMode].
  static final routingMode = obx.QueryStringProperty<AppSetting>(
    _entities[1].properties[12],
  );
}

/// [DeviceEntity] entity fields to define ObjectBox queries.
class DeviceEntity_ {
  /// See [DeviceEntity.id].
  static final id = obx.QueryIntegerProperty<DeviceEntity>(
    _entities[2].properties[0],
  );

  /// See [DeviceEntity.deviceId].
  static final deviceId = obx.QueryStringProperty<DeviceEntity>(
    _entities[2].properties[1],
  );

  /// See [DeviceEntity.name].
  static final name = obx.QueryStringProperty<DeviceEntity>(
    _entities[2].properties[2],
  );

  /// See [DeviceEntity.created].
  static final created = obx.QueryIntegerProperty<DeviceEntity>(
    _entities[2].properties[3],
  );
}

/// [PlanEntity] entity fields to define ObjectBox queries.
class PlanEntity_ {
  /// See [PlanEntity.id].
  static final id = obx.QueryIntegerProperty<PlanEntity>(
    _entities[3].properties[0],
  );

  /// See [PlanEntity.planId].
  static final planId = obx.QueryStringProperty<PlanEntity>(
    _entities[3].properties[1],
  );

  /// See [PlanEntity.description].
  static final description = obx.QueryStringProperty<PlanEntity>(
    _entities[3].properties[2],
  );

  /// See [PlanEntity.usdPrice].
  static final usdPrice = obx.QueryIntegerProperty<PlanEntity>(
    _entities[3].properties[3],
  );

  /// See [PlanEntity.priceJson].
  static final priceJson = obx.QueryStringProperty<PlanEntity>(
    _entities[3].properties[4],
  );

  /// See [PlanEntity.expectedMonthlyPriceJson].
  static final expectedMonthlyPriceJson = obx.QueryStringProperty<PlanEntity>(
    _entities[3].properties[5],
  );

  /// See [PlanEntity.bestValue].
  static final bestValue = obx.QueryBooleanProperty<PlanEntity>(
    _entities[3].properties[6],
  );
}

/// [PlansDataEntity] entity fields to define ObjectBox queries.
class PlansDataEntity_ {
  /// See [PlansDataEntity.id].
  static final id = obx.QueryIntegerProperty<PlansDataEntity>(
    _entities[4].properties[0],
  );

  /// See [PlansDataEntity.providers].
  static final providers =
      obx.QueryRelationToOne<PlansDataEntity, ProvidersEntity>(
        _entities[4].properties[1],
      );

  /// see [PlansDataEntity.plans]
  static final plans = obx.QueryRelationToMany<PlansDataEntity, PlanEntity>(
    _entities[4].relations[0],
  );
}

/// [PrivateServerEntity] entity fields to define ObjectBox queries.
class PrivateServerEntity_ {
  /// See [PrivateServerEntity.id].
  static final id = obx.QueryIntegerProperty<PrivateServerEntity>(
    _entities[5].properties[0],
  );

  /// See [PrivateServerEntity.serverName].
  static final serverName = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[1],
  );

  /// See [PrivateServerEntity.externalIp].
  static final externalIp = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[2],
  );

  /// See [PrivateServerEntity.port].
  static final port = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[3],
  );

  /// See [PrivateServerEntity.accessToken].
  static final accessToken = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[4],
  );

  /// See [PrivateServerEntity.isJoined].
  static final isJoined = obx.QueryBooleanProperty<PrivateServerEntity>(
    _entities[5].properties[5],
  );

  /// See [PrivateServerEntity.userSelected].
  static final userSelected = obx.QueryBooleanProperty<PrivateServerEntity>(
    _entities[5].properties[6],
  );

  /// See [PrivateServerEntity.serverLocationName].
  static final serverLocationName =
      obx.QueryStringProperty<PrivateServerEntity>(_entities[5].properties[7]);

  /// See [PrivateServerEntity.serverCountryCode].
  static final serverCountryCode = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[8],
  );

  /// See [PrivateServerEntity.protocol].
  static final protocol = obx.QueryStringProperty<PrivateServerEntity>(
    _entities[5].properties[9],
  );
}

/// [ProvidersEntity] entity fields to define ObjectBox queries.
class ProvidersEntity_ {
  /// See [ProvidersEntity.id].
  static final id = obx.QueryIntegerProperty<ProvidersEntity>(
    _entities[6].properties[0],
  );

  /// See [ProvidersEntity.androidJson].
  static final androidJson = obx.QueryStringProperty<ProvidersEntity>(
    _entities[6].properties[1],
  );

  /// See [ProvidersEntity.desktopJson].
  static final desktopJson = obx.QueryStringProperty<ProvidersEntity>(
    _entities[6].properties[2],
  );
}

/// [PurchaseEntity] entity fields to define ObjectBox queries.
class PurchaseEntity_ {
  /// See [PurchaseEntity.id].
  static final id = obx.QueryIntegerProperty<PurchaseEntity>(
    _entities[7].properties[0],
  );

  /// See [PurchaseEntity.plan].
  static final plan = obx.QueryStringProperty<PurchaseEntity>(
    _entities[7].properties[1],
  );
}

/// [SubscriptionDataEntity] entity fields to define ObjectBox queries.
class SubscriptionDataEntity_ {
  /// See [SubscriptionDataEntity.id].
  static final id = obx.QueryIntegerProperty<SubscriptionDataEntity>(
    _entities[8].properties[0],
  );

  /// See [SubscriptionDataEntity.planID].
  static final planID = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[1],
  );

  /// See [SubscriptionDataEntity.stripeCustomerID].
  static final stripeCustomerID =
      obx.QueryStringProperty<SubscriptionDataEntity>(
        _entities[8].properties[2],
      );

  /// See [SubscriptionDataEntity.startAt].
  static final startAt = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[3],
  );

  /// See [SubscriptionDataEntity.cancelledAt].
  static final cancelledAt = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[4],
  );

  /// See [SubscriptionDataEntity.autoRenew].
  static final autoRenew = obx.QueryBooleanProperty<SubscriptionDataEntity>(
    _entities[8].properties[5],
  );

  /// See [SubscriptionDataEntity.subscriptionID].
  static final subscriptionID = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[6],
  );

  /// See [SubscriptionDataEntity.status].
  static final status = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[7],
  );

  /// See [SubscriptionDataEntity.provider].
  static final provider = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[8],
  );

  /// See [SubscriptionDataEntity.createdAt].
  static final createdAt = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[9],
  );

  /// See [SubscriptionDataEntity.endAt].
  static final endAt = obx.QueryStringProperty<SubscriptionDataEntity>(
    _entities[8].properties[10],
  );
}

/// [UserDataEntity] entity fields to define ObjectBox queries.
class UserDataEntity_ {
  /// See [UserDataEntity.id].
  static final id = obx.QueryIntegerProperty<UserDataEntity>(
    _entities[9].properties[0],
  );

  /// See [UserDataEntity.userId].
  static final userId = obx.QueryIntegerProperty<UserDataEntity>(
    _entities[9].properties[1],
  );

  /// See [UserDataEntity.code].
  static final code = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[2],
  );

  /// See [UserDataEntity.token].
  static final token = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[3],
  );

  /// See [UserDataEntity.referral].
  static final referral = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[4],
  );

  /// See [UserDataEntity.phone].
  static final phone = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[5],
  );

  /// See [UserDataEntity.email].
  static final email = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[6],
  );

  /// See [UserDataEntity.userStatus].
  static final userStatus = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[7],
  );

  /// See [UserDataEntity.userLevel].
  static final userLevel = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[8],
  );

  /// See [UserDataEntity.locale].
  static final locale = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[9],
  );

  /// See [UserDataEntity.expiration].
  static final expiration = obx.QueryIntegerProperty<UserDataEntity>(
    _entities[9].properties[10],
  );

  /// See [UserDataEntity.subscription].
  static final subscription = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[11],
  );

  /// See [UserDataEntity.bonusDays].
  static final bonusDays = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[12],
  );

  /// See [UserDataEntity.bonusMonths].
  static final bonusMonths = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[13],
  );

  /// See [UserDataEntity.yinbiEnabled].
  static final yinbiEnabled = obx.QueryBooleanProperty<UserDataEntity>(
    _entities[9].properties[14],
  );

  /// See [UserDataEntity.servers].
  static final servers = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[15],
  );

  /// See [UserDataEntity.inviters].
  static final inviters = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[16],
  );

  /// See [UserDataEntity.invitees].
  static final invitees = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[17],
  );

  /// See [UserDataEntity.purchases].
  static final purchases = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[18],
  );

  /// See [UserDataEntity.subscriptionData].
  static final subscriptionData =
      obx.QueryRelationToOne<UserDataEntity, SubscriptionDataEntity>(
        _entities[9].properties[19],
      );

  /// See [UserDataEntity.deviceID].
  static final deviceID = obx.QueryStringProperty<UserDataEntity>(
    _entities[9].properties[20],
  );

  /// see [UserDataEntity.devices]
  static final devices = obx.QueryRelationToMany<UserDataEntity, DeviceEntity>(
    _entities[9].relations[0],
  );
}

/// [UserResponseEntity] entity fields to define ObjectBox queries.
class UserResponseEntity_ {
  /// See [UserResponseEntity.id].
  static final id = obx.QueryIntegerProperty<UserResponseEntity>(
    _entities[10].properties[0],
  );

  /// See [UserResponseEntity.legacyID].
  static final legacyID = obx.QueryIntegerProperty<UserResponseEntity>(
    _entities[10].properties[1],
  );

  /// See [UserResponseEntity.legacyToken].
  static final legacyToken = obx.QueryStringProperty<UserResponseEntity>(
    _entities[10].properties[2],
  );

  /// See [UserResponseEntity.emailConfirmed].
  static final emailConfirmed = obx.QueryBooleanProperty<UserResponseEntity>(
    _entities[10].properties[3],
  );

  /// See [UserResponseEntity.success].
  static final success = obx.QueryBooleanProperty<UserResponseEntity>(
    _entities[10].properties[4],
  );

  /// See [UserResponseEntity.legacyUserData].
  static final legacyUserData =
      obx.QueryRelationToOne<UserResponseEntity, UserDataEntity>(
        _entities[10].properties[5],
      );

  /// see [UserResponseEntity.devices]
  static final devices =
      obx.QueryRelationToMany<UserResponseEntity, DeviceEntity>(
        _entities[10].relations[0],
      );
}

/// [Website] entity fields to define ObjectBox queries.
class Website_ {
  /// See [Website.id].
  static final id = obx.QueryIntegerProperty<Website>(
    _entities[11].properties[0],
  );

  /// See [Website.domain].
  static final domain = obx.QueryStringProperty<Website>(
    _entities[11].properties[1],
  );
}

/// [ServerLocationEntity] entity fields to define ObjectBox queries.
class ServerLocationEntity_ {
  /// See [ServerLocationEntity.id].
  static final id = obx.QueryIntegerProperty<ServerLocationEntity>(
    _entities[12].properties[0],
  );

  /// See [ServerLocationEntity.serverName].
  static final serverName = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[1],
  );

  /// See [ServerLocationEntity.serverType].
  static final serverType = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[2],
  );

  /// See [ServerLocationEntity.countryCode].
  static final countryCode = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[3],
  );

  /// See [ServerLocationEntity.country].
  static final country = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[4],
  );

  /// See [ServerLocationEntity.city].
  static final city = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[5],
  );

  /// See [ServerLocationEntity.displayName].
  static final displayName = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[6],
  );

  /// See [ServerLocationEntity.autoLocationJson].
  static final autoLocationJson = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[7],
  );

  /// See [ServerLocationEntity.protocol].
  static final protocol = obx.QueryStringProperty<ServerLocationEntity>(
    _entities[12].properties[8],
  );
}

/// [DeveloperModeEntity] entity fields to define ObjectBox queries.
class DeveloperModeEntity_ {
  /// See [DeveloperModeEntity.id].
  static final id = obx.QueryIntegerProperty<DeveloperModeEntity>(
    _entities[13].properties[0],
  );

  /// See [DeveloperModeEntity.testPlayPurchaseEnabled].
  static final testPlayPurchaseEnabled =
      obx.QueryBooleanProperty<DeveloperModeEntity>(
        _entities[13].properties[1],
      );

  /// See [DeveloperModeEntity.testStripePurchaseEnabled].
  static final testStripePurchaseEnabled =
      obx.QueryBooleanProperty<DeveloperModeEntity>(
        _entities[13].properties[2],
      );
}
