sudo: false
language: go

services:
  - redis-server

go:
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get gopkg.in/bsm/ratelimit.v1
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/garyburd/redigo/redis
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv $HOME/gopath/src/github.com/go-redis/redis $HOME/gopath/src/gopkg.in/redis.v3
  - cd $HOME/gopath/src/gopkg.in/redis.v3
