/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/getlantern/lantern-outline/lantern-core/ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "ffi.go"

#include <stdlib.h>
#include "stdint.h"


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* setup(char* _logDir, char* _dataDir, char* _locale, int64_t logPort, int64_t appsPort, int64_t statusPort, void* api);
extern char* addSplitTunnelItem(char* filterTypeC, char* itemC);
extern char* removeSplitTunnelItem(char* filterTypeC, char* itemC);

// startVPN initializes and starts the VPN server if it is not already running.
//
extern char* startVPN();

// stopVPN stops the VPN server if it is running.
//
extern char* stopVPN();

// isVPNConnected checks if the VPN server is running and connected.
//
extern char* isVPNConnected();

// Get user data from the local config
//
extern char* getUserData();

// Fetch stipe subscription payment redirect link
//
extern char* stripeSubscriptionPaymentRedirect(char* subType);

// Fetch plans from the server
//
extern char* plans();

// OAuth methods
//
extern char* oauthLoginUrl(char* _provider);

// oauthLoginCallback is called when the user has logged in with OAuth and the callback URL is called.
//
extern char* oAuthLoginCallback(char* _oAuthToken);
extern void freeCString(char* cstr);
extern void enforce_binding();

#ifdef __cplusplus
}
#endif
