// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

class LanternBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LanternBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LanternBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int _GoStringLen(_GoString_ s) {
    return __GoStringLen(s);
  }

  late final __GoStringLenPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function(_GoString_)>>(
        '_GoStringLen',
      );
  late final __GoStringLen = __GoStringLenPtr
      .asFunction<int Function(_GoString_)>();

  ffi.Pointer<ffi.Char> _GoStringPtr(_GoString_ s) {
    return __GoStringPtr(s);
  }

  late final __GoStringPtrPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>>(
        '_GoStringPtr',
      );
  late final __GoStringPtr = __GoStringPtrPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(_GoString_)>();

  int __ctype_get_mb_cur_max() {
    return ___ctype_get_mb_cur_max();
  }

  late final ___ctype_get_mb_cur_maxPtr =
      _lookup<ffi.NativeFunction<ffi.Size Function()>>(
        '__ctype_get_mb_cur_max',
      );
  late final ___ctype_get_mb_cur_max = ___ctype_get_mb_cur_maxPtr
      .asFunction<int Function()>();

  double atof(ffi.Pointer<ffi.Char> __nptr) {
    return _atof(__nptr);
  }

  late final _atofPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.Char>)>>(
        'atof',
      );
  late final _atof = _atofPtr
      .asFunction<double Function(ffi.Pointer<ffi.Char>)>();

  int atoi(ffi.Pointer<ffi.Char> __nptr) {
    return _atoi(__nptr);
  }

  late final _atoiPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'atoi',
      );
  late final _atoi = _atoiPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int atol(ffi.Pointer<ffi.Char> __nptr) {
    return _atol(__nptr);
  }

  late final _atolPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ffi.Char>)>>(
        'atol',
      );
  late final _atol = _atolPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int atoll(ffi.Pointer<ffi.Char> __nptr) {
    return _atoll(__nptr);
  }

  late final _atollPtr =
      _lookup<ffi.NativeFunction<ffi.LongLong Function(ffi.Pointer<ffi.Char>)>>(
        'atoll',
      );
  late final _atoll = _atollPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  double strtod(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  ) {
    return _strtod(__nptr, __endptr);
  }

  late final _strtodPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Double Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('strtod');
  late final _strtod = _strtodPtr
      .asFunction<
        double Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  double strtof(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
  ) {
    return _strtof(__nptr, __endptr);
  }

  late final _strtofPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Float Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('strtof');
  late final _strtof = _strtofPtr
      .asFunction<
        double Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int strtol(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtol(__nptr, __endptr, __base);
  }

  late final _strtolPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Long Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtol');
  late final _strtol = _strtolPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  int strtoul(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoul(__nptr, __endptr, __base);
  }

  late final _strtoulPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtoul');
  late final _strtoul = _strtoulPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  int strtoq(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoq(__nptr, __endptr, __base);
  }

  late final _strtoqPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtoq');
  late final _strtoq = _strtoqPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  int strtouq(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtouq(__nptr, __endptr, __base);
  }

  late final _strtouqPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLongLong Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtouq');
  late final _strtouq = _strtouqPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  int strtoll(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoll(__nptr, __endptr, __base);
  }

  late final _strtollPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.LongLong Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtoll');
  late final _strtoll = _strtollPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  int strtoull(
    ffi.Pointer<ffi.Char> __nptr,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __endptr,
    int __base,
  ) {
    return _strtoull(__nptr, __endptr, __base);
  }

  late final _strtoullPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.UnsignedLongLong Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Int,
          )
        >
      >('strtoull');
  late final _strtoull = _strtoullPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int,
        )
      >();

  ffi.Pointer<ffi.Char> l64a(int __n) {
    return _l64a(__n);
  }

  late final _l64aPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Long)>>(
        'l64a',
      );
  late final _l64a = _l64aPtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int a64l(ffi.Pointer<ffi.Char> __s) {
    return _a64l(__s);
  }

  late final _a64lPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ffi.Char>)>>(
        'a64l',
      );
  late final _a64l = _a64lPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int select(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timeval> __timeout,
  ) {
    return _select(__nfds, __readfds, __writefds, __exceptfds, __timeout);
  }

  late final _selectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Pointer<fd_set>,
            ffi.Pointer<fd_set>,
            ffi.Pointer<fd_set>,
            ffi.Pointer<timeval>,
          )
        >
      >('select');
  late final _select = _selectPtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<timeval>,
        )
      >();

  int pselect(
    int __nfds,
    ffi.Pointer<fd_set> __readfds,
    ffi.Pointer<fd_set> __writefds,
    ffi.Pointer<fd_set> __exceptfds,
    ffi.Pointer<timespec> __timeout,
    ffi.Pointer<__sigset_t> __sigmask,
  ) {
    return _pselect(
      __nfds,
      __readfds,
      __writefds,
      __exceptfds,
      __timeout,
      __sigmask,
    );
  }

  late final _pselectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Int,
            ffi.Pointer<fd_set>,
            ffi.Pointer<fd_set>,
            ffi.Pointer<fd_set>,
            ffi.Pointer<timespec>,
            ffi.Pointer<__sigset_t>,
          )
        >
      >('pselect');
  late final _pselect = _pselectPtr
      .asFunction<
        int Function(
          int,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<fd_set>,
          ffi.Pointer<timespec>,
          ffi.Pointer<__sigset_t>,
        )
      >();

  int random() {
    return _random();
  }

  late final _randomPtr = _lookup<ffi.NativeFunction<ffi.Long Function()>>(
    'random',
  );
  late final _random = _randomPtr.asFunction<int Function()>();

  void srandom(int __seed) {
    return _srandom(__seed);
  }

  late final _srandomPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedInt)>>(
        'srandom',
      );
  late final _srandom = _srandomPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> initstate(
    int __seed,
    ffi.Pointer<ffi.Char> __statebuf,
    int __statelen,
  ) {
    return _initstate(__seed, __statebuf, __statelen);
  }

  late final _initstatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.UnsignedInt,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('initstate');
  late final _initstate = _initstatePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(int, ffi.Pointer<ffi.Char>, int)
      >();

  ffi.Pointer<ffi.Char> setstate(ffi.Pointer<ffi.Char> __statebuf) {
    return _setstate(__statebuf);
  }

  late final _setstatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('setstate');
  late final _setstate = _setstatePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int random_r(
    ffi.Pointer<random_data> __buf,
    ffi.Pointer<ffi.Int32> __result,
  ) {
    return _random_r(__buf, __result);
  }

  late final _random_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<random_data>, ffi.Pointer<ffi.Int32>)
        >
      >('random_r');
  late final _random_r = _random_rPtr
      .asFunction<
        int Function(ffi.Pointer<random_data>, ffi.Pointer<ffi.Int32>)
      >();

  int srandom_r(int __seed, ffi.Pointer<random_data> __buf) {
    return _srandom_r(__seed, __buf);
  }

  late final _srandom_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.UnsignedInt, ffi.Pointer<random_data>)
        >
      >('srandom_r');
  late final _srandom_r = _srandom_rPtr
      .asFunction<int Function(int, ffi.Pointer<random_data>)>();

  int initstate_r(
    int __seed,
    ffi.Pointer<ffi.Char> __statebuf,
    int __statelen,
    ffi.Pointer<random_data> __buf,
  ) {
    return _initstate_r(__seed, __statebuf, __statelen, __buf);
  }

  late final _initstate_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.UnsignedInt,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
            ffi.Pointer<random_data>,
          )
        >
      >('initstate_r');
  late final _initstate_r = _initstate_rPtr
      .asFunction<
        int Function(int, ffi.Pointer<ffi.Char>, int, ffi.Pointer<random_data>)
      >();

  int setstate_r(
    ffi.Pointer<ffi.Char> __statebuf,
    ffi.Pointer<random_data> __buf,
  ) {
    return _setstate_r(__statebuf, __buf);
  }

  late final _setstate_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<random_data>)
        >
      >('setstate_r');
  late final _setstate_r = _setstate_rPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<random_data>)
      >();

  int rand() {
    return _rand();
  }

  late final _randPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>('rand');
  late final _rand = _randPtr.asFunction<int Function()>();

  void srand(int __seed) {
    return _srand(__seed);
  }

  late final _srandPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedInt)>>('srand');
  late final _srand = _srandPtr.asFunction<void Function(int)>();

  int rand_r(ffi.Pointer<ffi.UnsignedInt> __seed) {
    return _rand_r(__seed);
  }

  late final _rand_rPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.UnsignedInt>)>
      >('rand_r');
  late final _rand_r = _rand_rPtr
      .asFunction<int Function(ffi.Pointer<ffi.UnsignedInt>)>();

  double drand48() {
    return _drand48();
  }

  late final _drand48Ptr = _lookup<ffi.NativeFunction<ffi.Double Function()>>(
    'drand48',
  );
  late final _drand48 = _drand48Ptr.asFunction<double Function()>();

  double erand48(ffi.Pointer<ffi.UnsignedShort> __xsubi) {
    return _erand48(__xsubi);
  }

  late final _erand48Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Double Function(ffi.Pointer<ffi.UnsignedShort>)>
      >('erand48');
  late final _erand48 = _erand48Ptr
      .asFunction<double Function(ffi.Pointer<ffi.UnsignedShort>)>();

  int lrand48() {
    return _lrand48();
  }

  late final _lrand48Ptr = _lookup<ffi.NativeFunction<ffi.Long Function()>>(
    'lrand48',
  );
  late final _lrand48 = _lrand48Ptr.asFunction<int Function()>();

  int nrand48(ffi.Pointer<ffi.UnsignedShort> __xsubi) {
    return _nrand48(__xsubi);
  }

  late final _nrand48Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>
      >('nrand48');
  late final _nrand48 = _nrand48Ptr
      .asFunction<int Function(ffi.Pointer<ffi.UnsignedShort>)>();

  int mrand48() {
    return _mrand48();
  }

  late final _mrand48Ptr = _lookup<ffi.NativeFunction<ffi.Long Function()>>(
    'mrand48',
  );
  late final _mrand48 = _mrand48Ptr.asFunction<int Function()>();

  int jrand48(ffi.Pointer<ffi.UnsignedShort> __xsubi) {
    return _jrand48(__xsubi);
  }

  late final _jrand48Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Long Function(ffi.Pointer<ffi.UnsignedShort>)>
      >('jrand48');
  late final _jrand48 = _jrand48Ptr
      .asFunction<int Function(ffi.Pointer<ffi.UnsignedShort>)>();

  void srand48(int __seedval) {
    return _srand48(__seedval);
  }

  late final _srand48Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Long)>>('srand48');
  late final _srand48 = _srand48Ptr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.UnsignedShort> seed48(
    ffi.Pointer<ffi.UnsignedShort> __seed16v,
  ) {
    return _seed48(__seed16v);
  }

  late final _seed48Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.UnsignedShort> Function(
            ffi.Pointer<ffi.UnsignedShort>,
          )
        >
      >('seed48');
  late final _seed48 = _seed48Ptr
      .asFunction<
        ffi.Pointer<ffi.UnsignedShort> Function(ffi.Pointer<ffi.UnsignedShort>)
      >();

  void lcong48(ffi.Pointer<ffi.UnsignedShort> __param) {
    return _lcong48(__param);
  }

  late final _lcong48Ptr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.UnsignedShort>)>
      >('lcong48');
  late final _lcong48 = _lcong48Ptr
      .asFunction<void Function(ffi.Pointer<ffi.UnsignedShort>)>();

  int drand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Double> __result,
  ) {
    return _drand48_r(__buffer, __result);
  }

  late final _drand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Double>)
        >
      >('drand48_r');
  late final _drand48_r = _drand48_rPtr
      .asFunction<
        int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Double>)
      >();

  int erand48_r(
    ffi.Pointer<ffi.UnsignedShort> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Double> __result,
  ) {
    return _erand48_r(__xsubi, __buffer, __result);
  }

  late final _erand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<drand48_data>,
            ffi.Pointer<ffi.Double>,
          )
        >
      >('erand48_r');
  late final _erand48_r = _erand48_rPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.UnsignedShort>,
          ffi.Pointer<drand48_data>,
          ffi.Pointer<ffi.Double>,
        )
      >();

  int lrand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Long> __result,
  ) {
    return _lrand48_r(__buffer, __result);
  }

  late final _lrand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
        >
      >('lrand48_r');
  late final _lrand48_r = _lrand48_rPtr
      .asFunction<
        int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
      >();

  int nrand48_r(
    ffi.Pointer<ffi.UnsignedShort> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Long> __result,
  ) {
    return _nrand48_r(__xsubi, __buffer, __result);
  }

  late final _nrand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<drand48_data>,
            ffi.Pointer<ffi.Long>,
          )
        >
      >('nrand48_r');
  late final _nrand48_r = _nrand48_rPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.UnsignedShort>,
          ffi.Pointer<drand48_data>,
          ffi.Pointer<ffi.Long>,
        )
      >();

  int mrand48_r(
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Long> __result,
  ) {
    return _mrand48_r(__buffer, __result);
  }

  late final _mrand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
        >
      >('mrand48_r');
  late final _mrand48_r = _mrand48_rPtr
      .asFunction<
        int Function(ffi.Pointer<drand48_data>, ffi.Pointer<ffi.Long>)
      >();

  int jrand48_r(
    ffi.Pointer<ffi.UnsignedShort> __xsubi,
    ffi.Pointer<drand48_data> __buffer,
    ffi.Pointer<ffi.Long> __result,
  ) {
    return _jrand48_r(__xsubi, __buffer, __result);
  }

  late final _jrand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<drand48_data>,
            ffi.Pointer<ffi.Long>,
          )
        >
      >('jrand48_r');
  late final _jrand48_r = _jrand48_rPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.UnsignedShort>,
          ffi.Pointer<drand48_data>,
          ffi.Pointer<ffi.Long>,
        )
      >();

  int srand48_r(int __seedval, ffi.Pointer<drand48_data> __buffer) {
    return _srand48_r(__seedval, __buffer);
  }

  late final _srand48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Long, ffi.Pointer<drand48_data>)
        >
      >('srand48_r');
  late final _srand48_r = _srand48_rPtr
      .asFunction<int Function(int, ffi.Pointer<drand48_data>)>();

  int seed48_r(
    ffi.Pointer<ffi.UnsignedShort> __seed16v,
    ffi.Pointer<drand48_data> __buffer,
  ) {
    return _seed48_r(__seed16v, __buffer);
  }

  late final _seed48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<drand48_data>,
          )
        >
      >('seed48_r');
  late final _seed48_r = _seed48_rPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.UnsignedShort>, ffi.Pointer<drand48_data>)
      >();

  int lcong48_r(
    ffi.Pointer<ffi.UnsignedShort> __param,
    ffi.Pointer<drand48_data> __buffer,
  ) {
    return _lcong48_r(__param, __buffer);
  }

  late final _lcong48_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.UnsignedShort>,
            ffi.Pointer<drand48_data>,
          )
        >
      >('lcong48_r');
  late final _lcong48_r = _lcong48_rPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.UnsignedShort>, ffi.Pointer<drand48_data>)
      >();

  int arc4random() {
    return _arc4random();
  }

  late final _arc4randomPtr =
      _lookup<ffi.NativeFunction<__uint32_t Function()>>('arc4random');
  late final _arc4random = _arc4randomPtr.asFunction<int Function()>();

  void arc4random_buf(ffi.Pointer<ffi.Void> __buf, int __size) {
    return _arc4random_buf(__buf, __size);
  }

  late final _arc4random_bufPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>
      >('arc4random_buf');
  late final _arc4random_buf = _arc4random_bufPtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>, int)>();

  int arc4random_uniform(int __upper_bound) {
    return _arc4random_uniform(__upper_bound);
  }

  late final _arc4random_uniformPtr =
      _lookup<ffi.NativeFunction<__uint32_t Function(__uint32_t)>>(
        'arc4random_uniform',
      );
  late final _arc4random_uniform = _arc4random_uniformPtr
      .asFunction<int Function(int)>();

  ffi.Pointer<ffi.Void> malloc(int __size) {
    return _malloc(__size);
  }

  late final _mallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
        'malloc',
      );
  late final _malloc = _mallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  ffi.Pointer<ffi.Void> calloc(int __nmemb, int __size) {
    return _calloc(__nmemb, __size);
  }

  late final _callocPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>
      >('calloc');
  late final _calloc = _callocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int, int)>();

  ffi.Pointer<ffi.Void> realloc(ffi.Pointer<ffi.Void> __ptr, int __size) {
    return _realloc(__ptr, __size);
  }

  late final _reallocPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Size)
        >
      >('realloc');
  late final _realloc = _reallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int)>();

  void free(ffi.Pointer<ffi.Void> __ptr) {
    return _free(__ptr);
  }

  late final _freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'free',
      );
  late final _free = _freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Void> reallocarray(
    ffi.Pointer<ffi.Void> __ptr,
    int __nmemb,
    int __size,
  ) {
    return _reallocarray(__ptr, __nmemb, __size);
  }

  late final _reallocarrayPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Size,
          )
        >
      >('reallocarray');
  late final _reallocarray = _reallocarrayPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, int, int)
      >();

  ffi.Pointer<ffi.Void> alloca(int __size) {
    return _alloca(__size);
  }

  late final _allocaPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
        'alloca',
      );
  late final _alloca = _allocaPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  ffi.Pointer<ffi.Void> valloc(int __size) {
    return _valloc(__size);
  }

  late final _vallocPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size)>>(
        'valloc',
      );
  late final _valloc = _vallocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int)>();

  int posix_memalign(
    ffi.Pointer<ffi.Pointer<ffi.Void>> __memptr,
    int __alignment,
    int __size,
  ) {
    return _posix_memalign(__memptr, __alignment, __size);
  }

  late final _posix_memalignPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Void>>,
            ffi.Size,
            ffi.Size,
          )
        >
      >('posix_memalign');
  late final _posix_memalign = _posix_memalignPtr
      .asFunction<int Function(ffi.Pointer<ffi.Pointer<ffi.Void>>, int, int)>();

  ffi.Pointer<ffi.Void> aligned_alloc(int __alignment, int __size) {
    return _aligned_alloc(__alignment, __size);
  }

  late final _aligned_allocPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Void> Function(ffi.Size, ffi.Size)>
      >('aligned_alloc');
  late final _aligned_alloc = _aligned_allocPtr
      .asFunction<ffi.Pointer<ffi.Void> Function(int, int)>();

  void abort() {
    return _abort();
  }

  late final _abortPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'abort',
  );
  late final _abort = _abortPtr.asFunction<void Function()>();

  int atexit(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __func) {
    return _atexit(__func);
  }

  late final _atexitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
        >
      >('atexit');
  late final _atexit = _atexitPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
      >();

  int at_quick_exit(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> __func,
  ) {
    return _at_quick_exit(__func);
  }

  late final _at_quick_exitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
        >
      >('at_quick_exit');
  late final _at_quick_exit = _at_quick_exitPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>)
      >();

  int on_exit(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int __status, ffi.Pointer<ffi.Void> __arg)
      >
    >
    __func,
    ffi.Pointer<ffi.Void> __arg,
  ) {
    return _on_exit(__func, __arg);
  }

  late final _on_exitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<
              ffi.NativeFunction<
                ffi.Void Function(ffi.Int __status, ffi.Pointer<ffi.Void> __arg)
              >
            >,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('on_exit');
  late final _on_exit = _on_exitPtr
      .asFunction<
        int Function(
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Int __status, ffi.Pointer<ffi.Void> __arg)
            >
          >,
          ffi.Pointer<ffi.Void>,
        )
      >();

  void exit(int __status) {
    return _exit(__status);
  }

  late final _exitPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
    'exit',
  );
  late final _exit = _exitPtr.asFunction<void Function(int)>();

  void quick_exit(int __status) {
    return _quick_exit(__status);
  }

  late final _quick_exitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('quick_exit');
  late final _quick_exit = _quick_exitPtr.asFunction<void Function(int)>();

  void _Exit(int __status) {
    return __Exit(__status);
  }

  late final __ExitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>('_Exit');
  late final __Exit = __ExitPtr.asFunction<void Function(int)>();

  ffi.Pointer<ffi.Char> getenv(ffi.Pointer<ffi.Char> __name) {
    return _getenv(__name);
  }

  late final _getenvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('getenv');
  late final _getenv = _getenvPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int putenv(ffi.Pointer<ffi.Char> __string) {
    return _putenv(__string);
  }

  late final _putenvPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'putenv',
      );
  late final _putenv = _putenvPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int setenv(
    ffi.Pointer<ffi.Char> __name,
    ffi.Pointer<ffi.Char> __value,
    int __replace,
  ) {
    return _setenv(__name, __value, __replace);
  }

  late final _setenvPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('setenv');
  late final _setenv = _setenvPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>, int)
      >();

  int unsetenv(ffi.Pointer<ffi.Char> __name) {
    return _unsetenv(__name);
  }

  late final _unsetenvPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'unsetenv',
      );
  late final _unsetenv = _unsetenvPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int clearenv() {
    return _clearenv();
  }

  late final _clearenvPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>(
    'clearenv',
  );
  late final _clearenv = _clearenvPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> mktemp(ffi.Pointer<ffi.Char> __template) {
    return _mktemp(__template);
  }

  late final _mktempPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('mktemp');
  late final _mktemp = _mktempPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int mkstemp(ffi.Pointer<ffi.Char> __template) {
    return _mkstemp(__template);
  }

  late final _mkstempPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'mkstemp',
      );
  late final _mkstemp = _mkstempPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int mkstemps(ffi.Pointer<ffi.Char> __template, int __suffixlen) {
    return _mkstemps(__template, __suffixlen);
  }

  late final _mkstempsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Int)>
      >('mkstemps');
  late final _mkstemps = _mkstempsPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  ffi.Pointer<ffi.Char> mkdtemp(ffi.Pointer<ffi.Char> __template) {
    return _mkdtemp(__template);
  }

  late final _mkdtempPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('mkdtemp');
  late final _mkdtemp = _mkdtempPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int system(ffi.Pointer<ffi.Char> __command) {
    return _system(__command);
  }

  late final _systemPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'system',
      );
  late final _system = _systemPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> realpath(
    ffi.Pointer<ffi.Char> __name,
    ffi.Pointer<ffi.Char> __resolved,
  ) {
    return _realpath(__name, __resolved);
  }

  late final _realpathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('realpath');
  late final _realpath = _realpathPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Void> bsearch(
    ffi.Pointer<ffi.Void> __key,
    ffi.Pointer<ffi.Void> __base,
    int __nmemb,
    int __size,
    __compar_fn_t __compar,
  ) {
    return _bsearch(__key, __base, __nmemb, __size, __compar);
  }

  late final _bsearchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Void> Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Size,
            __compar_fn_t,
          )
        >
      >('bsearch');
  late final _bsearch = _bsearchPtr
      .asFunction<
        ffi.Pointer<ffi.Void> Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<ffi.Void>,
          int,
          int,
          __compar_fn_t,
        )
      >();

  void qsort(
    ffi.Pointer<ffi.Void> __base,
    int __nmemb,
    int __size,
    __compar_fn_t __compar,
  ) {
    return _qsort(__base, __nmemb, __size, __compar);
  }

  late final _qsortPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<ffi.Void>,
            ffi.Size,
            ffi.Size,
            __compar_fn_t,
          )
        >
      >('qsort');
  late final _qsort = _qsortPtr
      .asFunction<
        void Function(ffi.Pointer<ffi.Void>, int, int, __compar_fn_t)
      >();

  int abs(int __x) {
    return _abs(__x);
  }

  late final _absPtr = _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Int)>>(
    'abs',
  );
  late final _abs = _absPtr.asFunction<int Function(int)>();

  int labs(int __x) {
    return _labs(__x);
  }

  late final _labsPtr =
      _lookup<ffi.NativeFunction<ffi.Long Function(ffi.Long)>>('labs');
  late final _labs = _labsPtr.asFunction<int Function(int)>();

  int llabs(int __x) {
    return _llabs(__x);
  }

  late final _llabsPtr =
      _lookup<ffi.NativeFunction<ffi.LongLong Function(ffi.LongLong)>>('llabs');
  late final _llabs = _llabsPtr.asFunction<int Function(int)>();

  div_t div(int __numer, int __denom) {
    return _div(__numer, __denom);
  }

  late final _divPtr =
      _lookup<ffi.NativeFunction<div_t Function(ffi.Int, ffi.Int)>>('div');
  late final _div = _divPtr.asFunction<div_t Function(int, int)>();

  ldiv_t ldiv(int __numer, int __denom) {
    return _ldiv(__numer, __denom);
  }

  late final _ldivPtr =
      _lookup<ffi.NativeFunction<ldiv_t Function(ffi.Long, ffi.Long)>>('ldiv');
  late final _ldiv = _ldivPtr.asFunction<ldiv_t Function(int, int)>();

  lldiv_t lldiv(int __numer, int __denom) {
    return _lldiv(__numer, __denom);
  }

  late final _lldivPtr =
      _lookup<ffi.NativeFunction<lldiv_t Function(ffi.LongLong, ffi.LongLong)>>(
        'lldiv',
      );
  late final _lldiv = _lldivPtr.asFunction<lldiv_t Function(int, int)>();

  ffi.Pointer<ffi.Char> ecvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int> __decpt,
    ffi.Pointer<ffi.Int> __sign,
  ) {
    return _ecvt(__value, __ndigit, __decpt, __sign);
  }

  late final _ecvtPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Double,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('ecvt');
  late final _ecvt = _ecvtPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          double,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  ffi.Pointer<ffi.Char> fcvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int> __decpt,
    ffi.Pointer<ffi.Int> __sign,
  ) {
    return _fcvt(__value, __ndigit, __decpt, __sign);
  }

  late final _fcvtPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Double,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('fcvt');
  late final _fcvt = _fcvtPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          double,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  ffi.Pointer<ffi.Char> gcvt(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Char> __buf,
  ) {
    return _gcvt(__value, __ndigit, __buf);
  }

  late final _gcvtPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Double,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('gcvt');
  late final _gcvt = _gcvtPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(double, int, ffi.Pointer<ffi.Char>)
      >();

  int ecvt_r(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int> __decpt,
    ffi.Pointer<ffi.Int> __sign,
    ffi.Pointer<ffi.Char> __buf,
    int __len,
  ) {
    return _ecvt_r(__value, __ndigit, __decpt, __sign, __buf, __len);
  }

  late final _ecvt_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Double,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('ecvt_r');
  late final _ecvt_r = _ecvt_rPtr
      .asFunction<
        int Function(
          double,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  int fcvt_r(
    double __value,
    int __ndigit,
    ffi.Pointer<ffi.Int> __decpt,
    ffi.Pointer<ffi.Int> __sign,
    ffi.Pointer<ffi.Char> __buf,
    int __len,
  ) {
    return _fcvt_r(__value, __ndigit, __decpt, __sign, __buf, __len);
  }

  late final _fcvt_rPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Double,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('fcvt_r');
  late final _fcvt_r = _fcvt_rPtr
      .asFunction<
        int Function(
          double,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  int mblen(ffi.Pointer<ffi.Char> __s, int __n) {
    return _mblen(__s, __n);
  }

  late final _mblenPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Size)>
      >('mblen');
  late final _mblen = _mblenPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  int mbtowc(ffi.Pointer<ffi.WChar> __pwc, ffi.Pointer<ffi.Char> __s, int __n) {
    return _mbtowc(__pwc, __s, __n);
  }

  late final _mbtowcPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('mbtowc');
  late final _mbtowc = _mbtowcPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, int)
      >();

  int wctomb(ffi.Pointer<ffi.Char> __s, int __wchar) {
    return _wctomb(__s, __wchar);
  }

  late final _wctombPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.WChar)>
      >('wctomb');
  late final _wctomb = _wctombPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int)>();

  int mbstowcs(
    ffi.Pointer<ffi.WChar> __pwcs,
    ffi.Pointer<ffi.Char> __s,
    int __n,
  ) {
    return _mbstowcs(__pwcs, __s, __n);
  }

  late final _mbstowcsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Size Function(
            ffi.Pointer<ffi.WChar>,
            ffi.Pointer<ffi.Char>,
            ffi.Size,
          )
        >
      >('mbstowcs');
  late final _mbstowcs = _mbstowcsPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.Char>, int)
      >();

  int wcstombs(
    ffi.Pointer<ffi.Char> __s,
    ffi.Pointer<ffi.WChar> __pwcs,
    int __n,
  ) {
    return _wcstombs(__s, __pwcs, __n);
  }

  late final _wcstombsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Size Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.WChar>,
            ffi.Size,
          )
        >
      >('wcstombs');
  late final _wcstombs = _wcstombsPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.WChar>, int)
      >();

  int rpmatch(ffi.Pointer<ffi.Char> __response) {
    return _rpmatch(__response);
  }

  late final _rpmatchPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'rpmatch',
      );
  late final _rpmatch = _rpmatchPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  int getsubopt(
    ffi.Pointer<ffi.Pointer<ffi.Char>> __optionp,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __tokens,
    ffi.Pointer<ffi.Pointer<ffi.Char>> __valuep,
  ) {
    return _getsubopt(__optionp, __tokens, __valuep);
  }

  late final _getsuboptPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('getsubopt');
  late final _getsubopt = _getsuboptPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
        )
      >();

  int getloadavg(ffi.Pointer<ffi.Double> __loadavg, int __nelem) {
    return _getloadavg(__loadavg, __nelem);
  }

  late final _getloadavgPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Double>, ffi.Int)>
      >('getloadavg');
  late final _getloadavg = _getloadavgPtr
      .asFunction<int Function(ffi.Pointer<ffi.Double>, int)>();

  ffi.Pointer<ffi.Char> setup(
    ffi.Pointer<ffi.Char> _logDir,
    ffi.Pointer<ffi.Char> _dataDir,
    ffi.Pointer<ffi.Char> _locale,
    ffi.Pointer<ffi.Char> _env,
    int logP,
    int appsP,
    int statusP,
    int privateServerP,
    int appEventP,
    int consent,
    ffi.Pointer<ffi.Void> api,
  ) {
    return _setup(
      _logDir,
      _dataDir,
      _locale,
      _env,
      logP,
      appsP,
      statusP,
      privateServerP,
      appEventP,
      consent,
      api,
    );
  }

  late final _setupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int64,
            ffi.Int64,
            ffi.Int64,
            ffi.Int64,
            ffi.Int64,
            ffi.Int,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('setup');
  late final _setup = _setupPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
          int,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Void>,
        )
      >();

  ffi.Pointer<ffi.Char> updateTelemetryConsent(int consent) {
    return _updateTelemetryConsent(consent);
  }

  late final _updateTelemetryConsentPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'updateTelemetryConsent',
      );
  late final _updateTelemetryConsent = _updateTelemetryConsentPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int isTelemetryEnabled() {
    return _isTelemetryEnabled();
  }

  late final _isTelemetryEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('isTelemetryEnabled');
  late final _isTelemetryEnabled = _isTelemetryEnabledPtr
      .asFunction<int Function()>();

  int isOAuthLogin() {
    return _isOAuthLogin();
  }

  late final _isOAuthLoginPtr = _lookup<ffi.NativeFunction<ffi.Int Function()>>(
    'isOAuthLogin',
  );
  late final _isOAuthLogin = _isOAuthLoginPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> getAppDataDir() {
    return _getAppDataDir();
  }

  late final _getAppDataDirPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getAppDataDir',
      );
  late final _getAppDataDir = _getAppDataDirPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getOAuthProvider() {
    return _getOAuthProvider();
  }

  late final _getOAuthProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getOAuthProvider',
      );
  late final _getOAuthProvider = _getOAuthProviderPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> availableFeatures() {
    return _availableFeatures();
  }

  late final _availableFeaturesPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'availableFeatures',
      );
  late final _availableFeatures = _availableFeaturesPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> updateLocale(ffi.Pointer<ffi.Char> _locale) {
    return _updateLocale(_locale);
  }

  late final _updateLocalePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('updateLocale');
  late final _updateLocale = _updateLocalePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> addSplitTunnelItem(
    ffi.Pointer<ffi.Char> filterTypeC,
    ffi.Pointer<ffi.Char> itemC,
  ) {
    return _addSplitTunnelItem(filterTypeC, itemC);
  }

  late final _addSplitTunnelItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('addSplitTunnelItem');
  late final _addSplitTunnelItem = _addSplitTunnelItemPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> removeSplitTunnelItem(
    ffi.Pointer<ffi.Char> filterTypeC,
    ffi.Pointer<ffi.Char> itemC,
  ) {
    return _removeSplitTunnelItem(filterTypeC, itemC);
  }

  late final _removeSplitTunnelItemPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('removeSplitTunnelItem');
  late final _removeSplitTunnelItem = _removeSplitTunnelItemPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> setSplitTunnelingEnabled(int enabled) {
    return _setSplitTunnelingEnabled(enabled);
  }

  late final _setSplitTunnelingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'setSplitTunnelingEnabled',
      );
  late final _setSplitTunnelingEnabled = _setSplitTunnelingEnabledPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int isSplitTunnelingEnabled() {
    return _isSplitTunnelingEnabled();
  }

  late final _isSplitTunnelingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'isSplitTunnelingEnabled',
      );
  late final _isSplitTunnelingEnabled = _isSplitTunnelingEnabledPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> loadInstalledApps(ffi.Pointer<ffi.Char> dataDir) {
    return _loadInstalledApps(dataDir);
  }

  late final _loadInstalledAppsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('loadInstalledApps');
  late final _loadInstalledApps = _loadInstalledAppsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> getDataCapInfo() {
    return _getDataCapInfo();
  }

  late final _getDataCapInfoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getDataCapInfo',
      );
  late final _getDataCapInfo = _getDataCapInfoPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> reportIssue(
    ffi.Pointer<ffi.Char> emailC,
    ffi.Pointer<ffi.Char> typeC,
    ffi.Pointer<ffi.Char> descC,
    ffi.Pointer<ffi.Char> deviceC,
    ffi.Pointer<ffi.Char> modelC,
    ffi.Pointer<ffi.Char> logPathC,
  ) {
    return _reportIssue(emailC, typeC, descC, deviceC, modelC, logPathC);
  }

  late final _reportIssuePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('reportIssue');
  late final _reportIssue = _reportIssuePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> getSelectedServerJSON() {
    return _getSelectedServerJSON();
  }

  late final _getSelectedServerJSONPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getSelectedServerJSON',
      );
  late final _getSelectedServerJSON = _getSelectedServerJSONPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getAutoLocation() {
    return _getAutoLocation();
  }

  late final _getAutoLocationPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getAutoLocation',
      );
  late final _getAutoLocation = _getAutoLocationPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> isTagAvailable(ffi.Pointer<ffi.Char> _tag) {
    return _isTagAvailable(_tag);
  }

  late final _isTagAvailablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('isTagAvailable');
  late final _isTagAvailable = _isTagAvailablePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> startAutoLocationListener() {
    return _startAutoLocationListener();
  }

  late final _startAutoLocationListenerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'startAutoLocationListener',
      );
  late final _startAutoLocationListener = _startAutoLocationListenerPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> stopAutoLocationListener() {
    return _stopAutoLocationListener();
  }

  late final _stopAutoLocationListenerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'stopAutoLocationListener',
      );
  late final _stopAutoLocationListener = _stopAutoLocationListenerPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getAvailableServers() {
    return _getAvailableServers();
  }

  late final _getAvailableServersPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getAvailableServers',
      );
  late final _getAvailableServers = _getAvailableServersPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> startVPN(
    ffi.Pointer<ffi.Char> _logDir,
    ffi.Pointer<ffi.Char> _dataDir,
    ffi.Pointer<ffi.Char> _locale,
  ) {
    return _startVPN(_logDir, _dataDir, _locale);
  }

  late final _startVPNPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('startVPN');
  late final _startVPN = _startVPNPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> stopVPN() {
    return _stopVPN();
  }

  late final _stopVPNPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('stopVPN');
  late final _stopVPN = _stopVPNPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> connectToServer(
    ffi.Pointer<ffi.Char> _location,
    ffi.Pointer<ffi.Char> _tag,
    ffi.Pointer<ffi.Char> _logDir,
    ffi.Pointer<ffi.Char> _dataDir,
    ffi.Pointer<ffi.Char> _locale,
  ) {
    return _connectToServer(_location, _tag, _logDir, _dataDir, _locale);
  }

  late final _connectToServerPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('connectToServer');
  late final _connectToServer = _connectToServerPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  int isVPNConnected() {
    return _isVPNConnected();
  }

  late final _isVPNConnectedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('isVPNConnected');
  late final _isVPNConnected = _isVPNConnectedPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> getUserData() {
    return _getUserData();
  }

  late final _getUserDataPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getUserData',
      );
  late final _getUserData = _getUserDataPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> fetchUserData() {
    return _fetchUserData();
  }

  late final _fetchUserDataPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'fetchUserData',
      );
  late final _fetchUserData = _fetchUserDataPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> stripeSubscriptionPaymentRedirect(
    ffi.Pointer<ffi.Char> subType,
    ffi.Pointer<ffi.Char> _planId,
    ffi.Pointer<ffi.Char> _email,
  ) {
    return _stripeSubscriptionPaymentRedirect(subType, _planId, _email);
  }

  late final _stripeSubscriptionPaymentRedirectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('stripeSubscriptionPaymentRedirect');
  late final _stripeSubscriptionPaymentRedirect =
      _stripeSubscriptionPaymentRedirectPtr
          .asFunction<
            ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  ffi.Pointer<ffi.Char> paymentRedirect(
    ffi.Pointer<ffi.Char> _plan,
    ffi.Pointer<ffi.Char> _provider,
    ffi.Pointer<ffi.Char> _email,
  ) {
    return _paymentRedirect(_plan, _provider, _email);
  }

  late final _paymentRedirectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('paymentRedirect');
  late final _paymentRedirect = _paymentRedirectPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> stripeBillingPortalUrl() {
    return _stripeBillingPortalUrl();
  }

  late final _stripeBillingPortalUrlPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'stripeBillingPortalUrl',
      );
  late final _stripeBillingPortalUrl = _stripeBillingPortalUrlPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> plans() {
    return _plans();
  }

  late final _plansPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>('plans');
  late final _plans = _plansPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> oauthLoginUrl(ffi.Pointer<ffi.Char> _provider) {
    return _oauthLoginUrl(_provider);
  }

  late final _oauthLoginUrlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('oauthLoginUrl');
  late final _oauthLoginUrl = _oauthLoginUrlPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> oAuthLoginCallback(ffi.Pointer<ffi.Char> _oAuthToken) {
    return _oAuthLoginCallback(_oAuthToken);
  }

  late final _oAuthLoginCallbackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('oAuthLoginCallback');
  late final _oAuthLoginCallback = _oAuthLoginCallbackPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> login(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _password,
  ) {
    return _login(_email, _password);
  }

  late final _loginPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('login');
  late final _login = _loginPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> signup(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _password,
  ) {
    return _signup(_email, _password);
  }

  late final _signupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('signup');
  late final _signup = _signupPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> logout(ffi.Pointer<ffi.Char> _email) {
    return _logout(_email);
  }

  late final _logoutPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('logout');
  late final _logout = _logoutPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> startRecoveryByEmail(ffi.Pointer<ffi.Char> _email) {
    return _startRecoveryByEmail(_email);
  }

  late final _startRecoveryByEmailPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('startRecoveryByEmail');
  late final _startRecoveryByEmail = _startRecoveryByEmailPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> validateEmailRecoveryCode(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _code,
  ) {
    return _validateEmailRecoveryCode(_email, _code);
  }

  late final _validateEmailRecoveryCodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('validateEmailRecoveryCode');
  late final _validateEmailRecoveryCode = _validateEmailRecoveryCodePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> completeRecoveryByEmail(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _newPassword,
    ffi.Pointer<ffi.Char> _code,
  ) {
    return _completeRecoveryByEmail(_email, _newPassword, _code);
  }

  late final _completeRecoveryByEmailPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('completeRecoveryByEmail');
  late final _completeRecoveryByEmail = _completeRecoveryByEmailPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> removeDevice(ffi.Pointer<ffi.Char> deviceId) {
    return _removeDevice(deviceId);
  }

  late final _removeDevicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('removeDevice');
  late final _removeDevice = _removeDevicePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> referralAttachment(
    ffi.Pointer<ffi.Char> _referralCode,
  ) {
    return _referralAttachment(_referralCode);
  }

  late final _referralAttachmentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('referralAttachment');
  late final _referralAttachment = _referralAttachmentPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> startChangeEmail(
    ffi.Pointer<ffi.Char> _newEmail,
    ffi.Pointer<ffi.Char> _password,
  ) {
    return _startChangeEmail(_newEmail, _password);
  }

  late final _startChangeEmailPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('startChangeEmail');
  late final _startChangeEmail = _startChangeEmailPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> completeChangeEmail(
    ffi.Pointer<ffi.Char> _newEmail,
    ffi.Pointer<ffi.Char> _password,
    ffi.Pointer<ffi.Char> _code,
  ) {
    return _completeChangeEmail(_newEmail, _password, _code);
  }

  late final _completeChangeEmailPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('completeChangeEmail');
  late final _completeChangeEmail = _completeChangeEmailPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> deleteAccount(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _password,
    int _isSSO,
  ) {
    return _deleteAccount(_email, _password, _isSSO);
  }

  late final _deleteAccountPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
          )
        >
      >('deleteAccount');
  late final _deleteAccount = _deleteAccountPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          int,
        )
      >();

  ffi.Pointer<ffi.Char> activationCode(
    ffi.Pointer<ffi.Char> _email,
    ffi.Pointer<ffi.Char> _resellerCode,
  ) {
    return _activationCode(_email, _resellerCode);
  }

  late final _activationCodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('activationCode');
  late final _activationCode = _activationCodePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  void freeCString(ffi.Pointer<ffi.Char> cstr) {
    return _freeCString(cstr);
  }

  late final _freeCStringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'freeCString',
      );
  late final _freeCString = _freeCStringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> digitalOceanPrivateServer() {
    return _digitalOceanPrivateServer();
  }

  late final _digitalOceanPrivateServerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'digitalOceanPrivateServer',
      );
  late final _digitalOceanPrivateServer = _digitalOceanPrivateServerPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> googleCloudPrivateServer() {
    return _googleCloudPrivateServer();
  }

  late final _googleCloudPrivateServerPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'googleCloudPrivateServer',
      );
  late final _googleCloudPrivateServer = _googleCloudPrivateServerPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> selectAccount(ffi.Pointer<ffi.Char> _account) {
    return _selectAccount(_account);
  }

  late final _selectAccountPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('selectAccount');
  late final _selectAccount = _selectAccountPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> selectProject(ffi.Pointer<ffi.Char> _project) {
    return _selectProject(_project);
  }

  late final _selectProjectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('selectProject');
  late final _selectProject = _selectProjectPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> validateSession() {
    return _validateSession();
  }

  late final _validateSessionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'validateSession',
      );
  late final _validateSession = _validateSessionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> startDepolyment(
    ffi.Pointer<ffi.Char> _selectedLocation,
    ffi.Pointer<ffi.Char> _serverName,
  ) {
    return _startDepolyment(_selectedLocation, _serverName);
  }

  late final _startDepolymentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('startDepolyment');
  late final _startDepolyment = _startDepolymentPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> cancelDepolyment() {
    return _cancelDepolyment();
  }

  late final _cancelDepolymentPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'cancelDepolyment',
      );
  late final _cancelDepolyment = _cancelDepolymentPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> addServerManagerInstance(
    ffi.Pointer<ffi.Char> _ip,
    ffi.Pointer<ffi.Char> _port,
    ffi.Pointer<ffi.Char> _accessToken,
    ffi.Pointer<ffi.Char> _tag,
  ) {
    return _addServerManagerInstance(_ip, _port, _accessToken, _tag);
  }

  late final _addServerManagerInstancePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('addServerManagerInstance');
  late final _addServerManagerInstance = _addServerManagerInstancePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> inviteToServerManagerInstance(
    ffi.Pointer<ffi.Char> _ip,
    ffi.Pointer<ffi.Char> _port,
    ffi.Pointer<ffi.Char> _accessToken,
    ffi.Pointer<ffi.Char> _inviteName,
  ) {
    return _inviteToServerManagerInstance(
      _ip,
      _port,
      _accessToken,
      _inviteName,
    );
  }

  late final _inviteToServerManagerInstancePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('inviteToServerManagerInstance');
  late final _inviteToServerManagerInstance = _inviteToServerManagerInstancePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> revokeServerManagerInvite(
    ffi.Pointer<ffi.Char> _ip,
    ffi.Pointer<ffi.Char> _port,
    ffi.Pointer<ffi.Char> _accessToken,
    ffi.Pointer<ffi.Char> _inviteName,
  ) {
    return _revokeServerManagerInvite(_ip, _port, _accessToken, _inviteName);
  }

  late final _revokeServerManagerInvitePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('revokeServerManagerInvite');
  late final _revokeServerManagerInvite = _revokeServerManagerInvitePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> addServerBasedOnURLs(
    ffi.Pointer<ffi.Char> _urls,
    int _skipCertVerification,
    ffi.Pointer<ffi.Char> _serverName,
  ) {
    return _addServerBasedOnURLs(_urls, _skipCertVerification, _serverName);
  }

  late final _addServerBasedOnURLsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('addServerBasedOnURLs');
  late final _addServerBasedOnURLs = _addServerBasedOnURLsPtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> setBlockAdsEnabled(int enabled) {
    return _setBlockAdsEnabled(enabled);
  }

  late final _setBlockAdsEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'setBlockAdsEnabled',
      );
  late final _setBlockAdsEnabled = _setBlockAdsEnabledPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int isBlockAdsEnabled() {
    return _isBlockAdsEnabled();
  }

  late final _isBlockAdsEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('isBlockAdsEnabled');
  late final _isBlockAdsEnabled = _isBlockAdsEnabledPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> setSmartRoutingEnabled(int enabled) {
    return _setSmartRoutingEnabled(enabled);
  }

  late final _setSmartRoutingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int)>>(
        'setSmartRoutingEnabled',
      );
  late final _setSmartRoutingEnabled = _setSmartRoutingEnabledPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  int isSmartRoutingEnabled() {
    return _isSmartRoutingEnabled();
  }

  late final _isSmartRoutingEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('isSmartRoutingEnabled');
  late final _isSmartRoutingEnabled = _isSmartRoutingEnabledPtr
      .asFunction<int Function()>();

  ffi.Pointer<ffi.Char> getSplitTunnelState() {
    return _getSplitTunnelState();
  }

  late final _getSplitTunnelStatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getSplitTunnelState',
      );
  late final _getSplitTunnelState = _getSplitTunnelStatePtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> getSplitTunnelItems(ffi.Pointer<ffi.Char> filterTypeC) {
    return _getSplitTunnelItems(filterTypeC);
  }

  late final _getSplitTunnelItemsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('getSplitTunnelItems');
  late final _getSplitTunnelItems = _getSplitTunnelItemsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> deletePrivateServerByName(ffi.Pointer<ffi.Char> _name) {
    return _deletePrivateServerByName(_name);
  }

  late final _deletePrivateServerByNamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
        >
      >('deletePrivateServerByName');
  late final _deletePrivateServerByName = _deletePrivateServerByNamePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  ffi.Pointer<ffi.Char> updatePrivateServerName(
    ffi.Pointer<ffi.Char> _oldName,
    ffi.Pointer<ffi.Char> _newName,
  ) {
    return _updatePrivateServerName(_oldName, _newName);
  }

  late final _updatePrivateServerNamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('updatePrivateServerName');
  late final _updatePrivateServerName = _updatePrivateServerNamePtr
      .asFunction<
        ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> getEnabledApps() {
    return _getEnabledApps();
  }

  late final _getEnabledAppsPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'getEnabledApps',
      );
  late final _getEnabledApps = _getEnabledAppsPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

typedef ptrdiff_t = ffi.Long;
typedef Dartptrdiff_t = int;

final class max_align_t extends ffi.Opaque {}

final class _GoString_ extends ffi.Struct {
  external ffi.Pointer<ffi.Char> p;

  @ptrdiff_t()
  external int n;
}

typedef _Float32 = ffi.Float;
typedef Dart_Float32 = double;
typedef _Float64 = ffi.Double;
typedef Dart_Float64 = double;
typedef _Float32x = ffi.Double;
typedef Dart_Float32x = double;

final class div_t extends ffi.Struct {
  @ffi.Int()
  external int quot;

  @ffi.Int()
  external int rem;
}

final class ldiv_t extends ffi.Struct {
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;
}

final class lldiv_t extends ffi.Struct {
  @ffi.LongLong()
  external int quot;

  @ffi.LongLong()
  external int rem;
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;

final class __fsid_t extends ffi.Struct {
  @ffi.Array.multi([2])
  external ffi.Array<ffi.Int> __val;
}

typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef u_char = __u_char;
typedef u_short = __u_short;
typedef u_int = __u_int;
typedef u_long = __u_long;
typedef quad_t = __quad_t;
typedef u_quad_t = __u_quad_t;
typedef fsid_t = __fsid_t;
typedef loff_t = __loff_t;
typedef ino_t = __ino_t;
typedef dev_t = __dev_t;
typedef gid_t = __gid_t;
typedef mode_t = __mode_t;
typedef nlink_t = __nlink_t;
typedef uid_t = __uid_t;
typedef off_t = __off_t;
typedef pid_t = __pid_t;
typedef id_t = __id_t;
typedef ssize_t = __ssize_t;
typedef daddr_t = __daddr_t;
typedef caddr_t = __caddr_t;
typedef key_t = __key_t;
typedef clock_t = __clock_t;
typedef clockid_t = __clockid_t;
typedef time_t = __time_t;
typedef timer_t = __timer_t;
typedef ulong = ffi.UnsignedLong;
typedef Dartulong = int;
typedef ushort = ffi.UnsignedShort;
typedef Dartushort = int;
typedef uint = ffi.UnsignedInt;
typedef Dartuint = int;
typedef u_int8_t = __uint8_t;
typedef u_int16_t = __uint16_t;
typedef u_int32_t = __uint32_t;
typedef u_int64_t = __uint64_t;
typedef register_t = ffi.Long;
typedef Dartregister_t = int;

final class __sigset_t extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedLong> __val;
}

typedef sigset_t = __sigset_t;

final class timeval extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__suseconds_t()
  external int tv_usec;
}

final class timespec extends ffi.Struct {
  @__time_t()
  external int tv_sec;

  @__syscall_slong_t()
  external int tv_nsec;
}

typedef suseconds_t = __suseconds_t;
typedef __fd_mask = ffi.Long;
typedef Dart__fd_mask = int;

final class fd_set extends ffi.Struct {
  @ffi.Array.multi([16])
  external ffi.Array<__fd_mask> __fds_bits;
}

typedef fd_mask = __fd_mask;
typedef blksize_t = __blksize_t;
typedef blkcnt_t = __blkcnt_t;
typedef fsblkcnt_t = __fsblkcnt_t;
typedef fsfilcnt_t = __fsfilcnt_t;

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

typedef __pthread_list_t = __pthread_internal_list;

final class __pthread_internal_slist extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_slist> __next;
}

typedef __pthread_slist_t = __pthread_internal_slist;

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Short()
  external int __spins;

  @ffi.Short()
  external int __unused;

  external __pthread_list_t __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.UnsignedLong()
  external int __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;

  @ffi.UnsignedInt()
  external int __unused_initialized_1;

  @ffi.UnsignedInt()
  external int __unused_initialized_2;
}

typedef __tss_t = ffi.UnsignedInt;
typedef Dart__tss_t = int;
typedef __thrd_t = ffi.UnsignedLong;
typedef Dart__thrd_t = int;

final class __once_flag extends ffi.Struct {
  @ffi.Int()
  external int __data;
}

typedef pthread_t = ffi.UnsignedLong;
typedef Dartpthread_t = int;

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef pthread_key_t = ffi.UnsignedInt;
typedef Dartpthread_key_t = int;
typedef pthread_once_t = ffi.Int;
typedef Dartpthread_once_t = int;

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class random_data extends ffi.Struct {
  external ffi.Pointer<ffi.Int32> fptr;

  external ffi.Pointer<ffi.Int32> rptr;

  external ffi.Pointer<ffi.Int32> state;

  @ffi.Int()
  external int rand_type;

  @ffi.Int()
  external int rand_deg;

  @ffi.Int()
  external int rand_sep;

  external ffi.Pointer<ffi.Int32> end_ptr;
}

final class drand48_data extends ffi.Struct {
  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedShort> __x;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedShort> __old_x;

  @ffi.UnsignedShort()
  external int __c;

  @ffi.UnsignedShort()
  external int __init;

  @ffi.UnsignedLongLong()
  external int __a;
}

typedef __compar_fn_tFunction =
    ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>);
typedef Dart__compar_fn_tFunction =
    int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>);
typedef __compar_fn_t = ffi.Pointer<ffi.NativeFunction<__compar_fn_tFunction>>;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;
typedef GoInt8 = ffi.SignedChar;
typedef DartGoInt8 = int;
typedef GoUint8 = ffi.UnsignedChar;
typedef DartGoUint8 = int;
typedef GoInt16 = ffi.Short;
typedef DartGoInt16 = int;
typedef GoUint16 = ffi.UnsignedShort;
typedef DartGoUint16 = int;
typedef GoInt32 = ffi.Int;
typedef DartGoInt32 = int;
typedef GoUint32 = ffi.UnsignedInt;
typedef DartGoUint32 = int;
typedef GoInt64 = ffi.LongLong;
typedef DartGoInt64 = int;
typedef GoUint64 = ffi.UnsignedLongLong;
typedef DartGoUint64 = int;
typedef GoInt = GoInt64;
typedef GoUint = GoUint64;
typedef GoUintptr = ffi.Size;
typedef DartGoUintptr = int;
typedef GoFloat32 = ffi.Float;
typedef DartGoFloat32 = double;
typedef GoFloat64 = ffi.Double;
typedef DartGoFloat64 = double;
typedef GoString = _GoString_;
typedef GoMap = ffi.Pointer<ffi.Void>;
typedef GoChan = ffi.Pointer<ffi.Void>;

final class GoInterface extends ffi.Struct {
  external ffi.Pointer<ffi.Void> t;

  external ffi.Pointer<ffi.Void> v;
}

final class GoSlice extends ffi.Struct {
  external ffi.Pointer<ffi.Void> data;

  @GoInt()
  external int len;

  @GoInt()
  external int cap;
}

const int NULL = 0;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2Y = 1;

const int __GLIBC_USE_ISOC23 = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 202405;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __USE_XOPEN2K24 = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_TIME_BITS64 = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C23_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 43;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _STDLIB_H = 1;

const int WNOHANG = 1;

const int WUNTRACED = 2;

const int WSTOPPED = 2;

const int WEXITED = 4;

const int WCONTINUED = 8;

const int WNOWAIT = 16777216;

const int __WNOTHREAD = 536870912;

const int __WALL = 1073741824;

const int __WCLONE = 2147483648;

const int __W_CONTINUED = 65535;

const int __WCOREFLAG = 128;

const int __HAVE_FLOAT128 = 1;

const int __HAVE_DISTINCT_FLOAT128 = 1;

const int __HAVE_FLOAT64X = 1;

const int __HAVE_FLOAT64X_LONG_DOUBLE = 1;

const int __HAVE_FLOAT16 = 0;

const int __HAVE_FLOAT32 = 1;

const int __HAVE_FLOAT64 = 1;

const int __HAVE_FLOAT32X = 1;

const int __HAVE_FLOAT128X = 0;

const int __HAVE_DISTINCT_FLOAT16 = 0;

const int __HAVE_DISTINCT_FLOAT32 = 0;

const int __HAVE_DISTINCT_FLOAT64 = 0;

const int __HAVE_DISTINCT_FLOAT32X = 0;

const int __HAVE_DISTINCT_FLOAT64X = 0;

const int __HAVE_DISTINCT_FLOAT128X = 0;

const int __HAVE_FLOAT128_UNLIKE_LDBL = 1;

const int __HAVE_FLOATN_NOT_TYPEDEF = 0;

const int __ldiv_t_defined = 1;

const int __lldiv_t_defined = 1;

const int RAND_MAX = 2147483647;

const int EXIT_FAILURE = 1;

const int EXIT_SUCCESS = 0;

const int _SYS_TYPES_H = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int __clock_t_defined = 1;

const int __clockid_t_defined = 1;

const int __time_t_defined = 1;

const int __timer_t_defined = 1;

const int _BITS_STDINT_INTN_H = 1;

const int __BIT_TYPES_DEFINED__ = 1;

const int _ENDIAN_H = 1;

const int _BITS_ENDIAN_H = 1;

const int __LITTLE_ENDIAN = 1234;

const int __BIG_ENDIAN = 4321;

const int __PDP_ENDIAN = 3412;

const int _BITS_ENDIANNESS_H = 1;

const int __BYTE_ORDER = 1234;

const int __FLOAT_WORD_ORDER = 1234;

const int LITTLE_ENDIAN = 1234;

const int BIG_ENDIAN = 4321;

const int PDP_ENDIAN = 3412;

const int BYTE_ORDER = 1234;

const int _BITS_BYTESWAP_H = 1;

const int _BITS_UINTN_IDENTITY_H = 1;

const int _SYS_SELECT_H = 1;

const int __sigset_t_defined = 1;

const int _SIGSET_NWORDS = 16;

const int __timeval_defined = 1;

const int _STRUCT_TIMESPEC = 1;

const int __NFDBITS = 64;

const int FD_SETSIZE = 1024;

const int NFDBITS = 64;

const int _BITS_PTHREADTYPES_COMMON_H = 1;

const int _THREAD_SHARED_TYPES_H = 1;

const int _BITS_PTHREADTYPES_ARCH_H = 1;

const int __SIZEOF_PTHREAD_MUTEX_T = 40;

const int __SIZEOF_PTHREAD_ATTR_T = 56;

const int __SIZEOF_PTHREAD_RWLOCK_T = 56;

const int __SIZEOF_PTHREAD_BARRIER_T = 32;

const int __SIZEOF_PTHREAD_MUTEXATTR_T = 4;

const int __SIZEOF_PTHREAD_COND_T = 48;

const int __SIZEOF_PTHREAD_CONDATTR_T = 4;

const int __SIZEOF_PTHREAD_RWLOCKATTR_T = 8;

const int __SIZEOF_PTHREAD_BARRIERATTR_T = 4;

const int _THREAD_MUTEX_INTERNAL_H = 1;

const int __PTHREAD_MUTEX_HAVE_PREV = 1;

const int __have_pthread_attr_t = 1;

const int _ALLOCA_H = 1;

const int _STDINT_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;
