// Package currency provides the list of currency codes
package currency

import (
	stripe "github.com/stripe/stripe-go"
)

const (
	AED stripe.Currency = "aed" // United Arab Emirates Dirham
	AFN stripe.Currency = "afn" // Afghan Afghani
	ALL stripe.Currency = "all" // Albanian Lek
	AMD stripe.Currency = "amd" // Armenian Dram
	ANG stripe.Currency = "ang" // Netherlands Antillean Gulden
	AOA stripe.Currency = "aoa" // Angolan Kwanza
	ARS stripe.Currency = "ars" // Argentine Peso
	AUD stripe.Currency = "aud" // Australian Dollar
	AWG stripe.Currency = "awg" // Aruban Florin
	AZN stripe.Currency = "azn" // Azerbaijani Manat
	BAM stripe.Currency = "bam" // Bosnia & Herzegovina Convertible Mark
	BBD stripe.Currency = "bbd" // Barbadian Dollar
	BDT stripe.Currency = "bdt" // Bangladeshi Taka
	BGN stripe.Currency = "bgn" // Bulgarian Lev
	BIF stripe.Currency = "bif" // Burundian Franc
	BMD stripe.Currency = "bmd" // Bermudian Dollar
	BND stripe.Currency = "bnd" // Brunei Dollar
	BOB stripe.Currency = "bob" // Bolivian Boliviano
	BRL stripe.Currency = "brl" // Brazilian Real
	BSD stripe.Currency = "bsd" // Bahamian Dollar
	BWP stripe.Currency = "bwp" // Botswana Pula
	BZD stripe.Currency = "bzd" // Belize Dollar
	CAD stripe.Currency = "cad" // Canadian Dollar
	CDF stripe.Currency = "cdf" // Congolese Franc
	CHF stripe.Currency = "chf" // Swiss Franc
	CLP stripe.Currency = "clp" // Chilean Peso
	CNY stripe.Currency = "cny" // Chinese Renminbi Yuan
	COP stripe.Currency = "cop" // Colombian Peso
	CRC stripe.Currency = "crc" // Costa Rican Colón
	CVE stripe.Currency = "cve" // Cape Verdean Escudo
	CZK stripe.Currency = "czk" // Czech Koruna
	DJF stripe.Currency = "djf" // Djiboutian Franc
	DKK stripe.Currency = "dkk" // Danish Krone
	DOP stripe.Currency = "dop" // Dominican Peso
	DZD stripe.Currency = "dzd" // Algerian Dinar
	EEK stripe.Currency = "eek" // Estonian Kroon
	EGP stripe.Currency = "egp" // Egyptian Pound
	ETB stripe.Currency = "etb" // Ethiopian Birr
	EUR stripe.Currency = "eur" // Euro
	FJD stripe.Currency = "fjd" // Fijian Dollar
	FKP stripe.Currency = "fkp" // Falkland Islands Pound
	GBP stripe.Currency = "gbp" // British Pound
	GEL stripe.Currency = "gel" // Georgian Lari
	GIP stripe.Currency = "gip" // Gibraltar Pound
	GMD stripe.Currency = "gmd" // Gambian Dalasi
	GNF stripe.Currency = "gnf" // Guinean Franc
	GTQ stripe.Currency = "gtq" // Guatemalan Quetzal
	GYD stripe.Currency = "gyd" // Guyanese Dollar
	HKD stripe.Currency = "hkd" // Hong Kong Dollar
	HNL stripe.Currency = "hnl" // Honduran Lempira
	HRK stripe.Currency = "hrk" // Croatian Kuna
	HTG stripe.Currency = "htg" // Haitian Gourde
	HUF stripe.Currency = "huf" // Hungarian Forint
	IDR stripe.Currency = "idr" // Indonesian Rupiah
	ILS stripe.Currency = "ils" // Israeli New Sheqel
	INR stripe.Currency = "inr" // Indian Rupee
	ISK stripe.Currency = "isk" // Icelandic Króna
	JMD stripe.Currency = "jmd" // Jamaican Dollar
	JPY stripe.Currency = "jpy" // Japanese Yen
	KES stripe.Currency = "kes" // Kenyan Shilling
	KGS stripe.Currency = "kgs" // Kyrgyzstani Som
	KHR stripe.Currency = "khr" // Cambodian Riel
	KMF stripe.Currency = "kmf" // Comorian Franc
	KRW stripe.Currency = "krw" // South Korean Won
	KYD stripe.Currency = "kyd" // Cayman Islands Dollar
	KZT stripe.Currency = "kzt" // Kazakhstani Tenge
	LAK stripe.Currency = "lak" // Lao Kip
	LBP stripe.Currency = "lbp" // Lebanese Pound
	LKR stripe.Currency = "lkr" // Sri Lankan Rupee
	LRD stripe.Currency = "lrd" // Liberian Dollar
	LSL stripe.Currency = "lsl" // Lesotho Loti
	LTL stripe.Currency = "ltl" // Lithuanian Litas
	LVL stripe.Currency = "lvl" // Latvian Lats
	MAD stripe.Currency = "mad" // Moroccan Dirham
	MDL stripe.Currency = "mdl" // Moldovan Leu
	MGA stripe.Currency = "mga" // Malagasy Ariary
	MKD stripe.Currency = "mkd" // Macedonian Denar
	MNT stripe.Currency = "mnt" // Mongolian Tögrög
	MOP stripe.Currency = "mop" // Macanese Pataca
	MRO stripe.Currency = "mro" // Mauritanian Ouguiya
	MUR stripe.Currency = "mur" // Mauritian Rupee
	MVR stripe.Currency = "mvr" // Maldivian Rufiyaa
	MWK stripe.Currency = "mwk" // Malawian Kwacha
	MXN stripe.Currency = "mxn" // Mexican Peso
	MYR stripe.Currency = "myr" // Malaysian Ringgit
	MZN stripe.Currency = "mzn" // Mozambican Metical
	NAD stripe.Currency = "nad" // Namibian Dollar
	NGN stripe.Currency = "ngn" // Nigerian Naira
	NIO stripe.Currency = "nio" // Nicaraguan Córdoba
	NOK stripe.Currency = "nok" // Norwegian Krone
	NPR stripe.Currency = "npr" // Nepalese Rupee
	NZD stripe.Currency = "nzd" // New Zealand Dollar
	PAB stripe.Currency = "pab" // Panamanian Balboa
	PEN stripe.Currency = "pen" // Peruvian Nuevo Sol
	PGK stripe.Currency = "pgk" // Papua New Guinean Kina
	PHP stripe.Currency = "php" // Philippine Peso
	PKR stripe.Currency = "pkr" // Pakistani Rupee
	PLN stripe.Currency = "pln" // Polish Złoty
	PYG stripe.Currency = "pyg" // Paraguayan Guaraní
	QAR stripe.Currency = "qar" // Qatari Riyal
	RON stripe.Currency = "ron" // Romanian Leu
	RSD stripe.Currency = "rsd" // Serbian Dinar
	RUB stripe.Currency = "rub" // Russian Ruble
	RWF stripe.Currency = "rwf" // Rwandan Franc
	SAR stripe.Currency = "sar" // Saudi Riyal
	SBD stripe.Currency = "sbd" // Solomon Islands Dollar
	SCR stripe.Currency = "scr" // Seychellois Rupee
	SEK stripe.Currency = "sek" // Swedish Krona
	SGD stripe.Currency = "sgd" // Singapore Dollar
	SHP stripe.Currency = "shp" // Saint Helenian Pound
	SLL stripe.Currency = "sll" // Sierra Leonean Leone
	SOS stripe.Currency = "sos" // Somali Shilling
	SRD stripe.Currency = "srd" // Surinamese Dollar
	STD stripe.Currency = "std" // São Tomé and Príncipe Dobra
	SVC stripe.Currency = "svc" // Salvadoran Colón
	SZL stripe.Currency = "szl" // Swazi Lilangeni
	THB stripe.Currency = "thb" // Thai Baht
	TJS stripe.Currency = "tjs" // Tajikistani Somoni
	TOP stripe.Currency = "top" // Tongan Paʻanga
	TRY stripe.Currency = "try" // Turkish Lira
	TTD stripe.Currency = "ttd" // Trinidad and Tobago Dollar
	TWD stripe.Currency = "twd" // New Taiwan Dollar
	TZS stripe.Currency = "tzs" // Tanzanian Shilling
	UAH stripe.Currency = "uah" // Ukrainian Hryvnia
	UGX stripe.Currency = "ugx" // Ugandan Shilling
	USD stripe.Currency = "usd" // United States Dollar
	UYU stripe.Currency = "uyu" // Uruguayan Peso
	UZS stripe.Currency = "uzs" // Uzbekistani Som
	VEF stripe.Currency = "vef" // Venezuelan Bolívar
	VND stripe.Currency = "vnd" // Vietnamese Đồng
	VUV stripe.Currency = "vuv" // Vanuatu Vatu
	WST stripe.Currency = "wst" // Samoan Tala
	XAF stripe.Currency = "xaf" // Central African Cfa Franc
	XCD stripe.Currency = "xcd" // East Caribbean Dollar
	XOF stripe.Currency = "xof" // West African Cfa Franc
	XPF stripe.Currency = "xpf" // Cfp Franc
	YER stripe.Currency = "yer" // Yemeni Rial
	ZAR stripe.Currency = "zar" // South African Rand
	ZMW stripe.Currency = "zmw" // Zambian Kwacha
)
