/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/getlantern/lantern/lantern-core/ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 5 "ffi.go"

#include <stdlib.h>
#include "stdint.h"


#line 1 "cgo-generated-wrapper"

#line 5 "platform_interface_darwin.go"

#include <stdlib.h>
#include <stdint.h>

// Callback typedefs for PlatformInterface
// OpenTun: opens a TUN device with the given options (JSON), returns fd via ret0_
typedef int32_t (*OpenTunCallback)(const char* tunOptionsJson, int32_t* fd);
typedef void (*ClearDNSCacheCallback)(void);
typedef void (*WriteLogCallback)(const char* message);
typedef int (*RestartServiceCallback)(void);
typedef void (*PostServiceCloseCallback)(void);
typedef int (*UsePlatformAutoDetectControlCallback)(void);
typedef char* (*ReadWIFIStateCallback)(void);
typedef int (*UnderNetworkExtensionCallback)(void);
typedef int (*IncludeAllNetworksCallback)(void);
typedef void (*SwiftEventCallback)(const char* eventJson);

// Callbacks storage struct - avoids multiple definitions
typedef struct {
    OpenTunCallback openTun;
    ClearDNSCacheCallback clearDNSCache;
    WriteLogCallback writeLog;
    RestartServiceCallback restartService;
    PostServiceCloseCallback postServiceClose;
    UsePlatformAutoDetectControlCallback usePlatformAutoDetectControl;
    ReadWIFIStateCallback readWIFIState;
    UnderNetworkExtensionCallback underNetworkExtension;
    IncludeAllNetworksCallback includeAllNetworks;
    SwiftEventCallback swiftEvent;
} PlatformCallbacks;

// Single static struct instance
static PlatformCallbacks platformCallbacks = {0};

// Wrapper functions called from Go
static inline void setPlatformCallbacks(
    OpenTunCallback openTun,
    ClearDNSCacheCallback clearDNSCache,
    WriteLogCallback writeLog,
    RestartServiceCallback restartService,
    PostServiceCloseCallback postServiceClose,
    UsePlatformAutoDetectControlCallback usePlatformAutoDetectControl,
    ReadWIFIStateCallback readWIFIState,
    UnderNetworkExtensionCallback underNetworkExtension,
    IncludeAllNetworksCallback includeAllNetworks
) {
    platformCallbacks.openTun = openTun;
    platformCallbacks.clearDNSCache = clearDNSCache;
    platformCallbacks.writeLog = writeLog;
    platformCallbacks.restartService = restartService;
    platformCallbacks.postServiceClose = postServiceClose;
    platformCallbacks.usePlatformAutoDetectControl = usePlatformAutoDetectControl;
    platformCallbacks.readWIFIState = readWIFIState;
    platformCallbacks.underNetworkExtension = underNetworkExtension;
    platformCallbacks.includeAllNetworks = includeAllNetworks;
}

static inline void setSwiftEventCallback(SwiftEventCallback cb) {
    platformCallbacks.swiftEvent = cb;
}

static inline int hasPlatformCallbacksSet(void) {
    return platformCallbacks.openTun != NULL;
}

static inline int32_t callOpenTun(const char* opts, int32_t* fd) {
    if (platformCallbacks.openTun != NULL) {
        return platformCallbacks.openTun(opts, fd);
    }
    return -1;
}

static inline void callClearDNSCache(void) {
    if (platformCallbacks.clearDNSCache != NULL) {
        platformCallbacks.clearDNSCache();
    }
}

static inline void callWriteLog(const char* message) {
    if (platformCallbacks.writeLog != NULL) {
        platformCallbacks.writeLog(message);
    }
}

static inline int callRestartService(void) {
    if (platformCallbacks.restartService != NULL) {
        return platformCallbacks.restartService();
    }
    return -1;
}

static inline void callPostServiceClose(void) {
    if (platformCallbacks.postServiceClose != NULL) {
        platformCallbacks.postServiceClose();
    }
}

static inline int callUsePlatformAutoDetectControl(void) {
    if (platformCallbacks.usePlatformAutoDetectControl != NULL) {
        return platformCallbacks.usePlatformAutoDetectControl();
    }
    return 0;
}

static inline char* callReadWIFIState(void) {
    if (platformCallbacks.readWIFIState != NULL) {
        return platformCallbacks.readWIFIState();
    }
    return NULL;
}

static inline int callUnderNetworkExtension(void) {
    if (platformCallbacks.underNetworkExtension != NULL) {
        return platformCallbacks.underNetworkExtension();
    }
    return 0;
}

static inline int callIncludeAllNetworks(void) {
    if (platformCallbacks.includeAllNetworks != NULL) {
        return platformCallbacks.includeAllNetworks();
    }
    return 0;
}

static inline void callSwiftEventCallback(const char* eventJson) {
    if (platformCallbacks.swiftEvent != NULL) {
        platformCallbacks.swiftEvent(eventJson);
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* setup(char* _logDir, char* _dataDir, char* _locale, int64_t logP, int64_t appsP, int64_t statusP, int64_t privateServerP, int64_t appEventP, int consent, void* api);

// updateTelemetryConsent updates the telemetry consent.
//
extern char* updateTelemetryConsent(int consent);

// availableFeatures returns a list of available features in JSON format.
//
extern char* availableFeatures(void);
extern char* updateLocale(char* _locale);
extern char* addSplitTunnelItem(char* filterTypeC, char* itemC);
extern char* removeSplitTunnelItem(char* filterTypeC, char* itemC);
extern char* setSplitTunnelingEnabled(int enabled);
extern int isSplitTunnelingEnabled(void);
extern char* loadInstalledApps(char* dataDir);
extern char* getDataCapInfo(void);
extern char* reportIssue(char* emailC, char* typeC, char* descC, char* deviceC, char* modelC, char* logPathC);

// startVPN initializes and starts the VPN server if it is not already running.
//
extern char* startVPN(char* _logDir, char* _dataDir, char* _locale);

// stopVPN stops the VPN server if it is running.
//
extern char* stopVPN(void);

// getAutoLocation returns the auto location in JSON format.
//
extern char* getAutoLocation(void);

// startAutoLocationListener starts the auto location listener.
//
extern char* startAutoLocationListener(void);

// stopAutoLocationListener stops the auto location listener.
//
extern char* stopAutoLocationListener(void);

// GetAvailableServers returns the available servers in JSON format.
//
extern char* getAvailableServers(void);

// connectToServer sets the private server with the given tag.
// connectToServer connects to a specific VPN server identified by the location type and tag.
// connectToServer will open and start the VPN tunnel if it is not already running.
//
extern char* connectToServer(char* _location, char* _tag, char* _logDir, char* _dataDir, char* _locale);

// isVPNConnected checks if the VPN server is running and connected.
//
extern int isVPNConnected(void);

// APIS
// Get user data from the local config
//
extern char* getUserData(void);

// Get user data from the server
//
extern char* fetchUserData(void);

// Fetch stipe subscription payment redirect link
//
extern char* stripeSubscriptionPaymentRedirect(char* subType, char* _planId, char* _email);

// Fetch payment redirect link for providers like alipay
//
extern char* paymentRedirect(char* _plan, char* _provider, char* _email);

// Fetch stripe subscription link
//
extern char* stripeBillingPortalUrl(void);

// Fetch plans from the server
//
extern char* plans(void);

// OAuth methods
//
extern char* oauthLoginUrl(char* _provider);
extern char* oAuthLoginCallback(char* _oAuthToken);

// User management
//
// login is called when the user logs in with email and password.
//
extern char* login(char* _email, char* _password);
extern char* signup(char* _email, char* _password);
extern char* logout(char* _email);

// startRecoveryByEmail will send recovery code to the email
//
extern char* startRecoveryByEmail(char* _email);

// Validate email recovery code
//
extern char* validateEmailRecoveryCode(char* _email, char* _code);

// Complete recovery by email
//
extern char* completeRecoveryByEmail(char* _email, char* _newPassword, char* _code);

// removeDevice removes a device by its ID.
//
extern char* removeDevice(char* deviceId);

// referralAttachment attaches a referral code to the user's account.
//
extern char* referralAttachment(char* _referralCode);

// startChangeEmail initiates the process of changing the user's email address.
//
extern char* startChangeEmail(char* _newEmail, char* _password);

// completeChangeEmail completes the process of changing the user's email address.
//
extern char* completeChangeEmail(char* _newEmail, char* _password, char* _code);

// Delete account permanently
//
extern char* deleteAccount(char* _email, char* _password);

// activationCode create subscription using activation code
//
extern char* activationCode(char* _email, char* _resellerCode);
extern void freeCString(char* cstr);

// digitalOceanPrivateServer starts the DigitalOcean private server flow.
//
extern char* digitalOceanPrivateServer(void);

// googleCloudPrivateServer starts the Google Cloud private server flow.
//
extern char* googleCloudPrivateServer(void);

// selectAccount selects the account for the private server.
//
extern char* selectAccount(char* _account);

// selectedProject selects the project for the private server.
//
extern char* selectProject(char* _project);

// validateSession validates the session for the private server.
//
extern char* validateSession(void);

// startDepolyment starts the deployment for the private server.
//
extern char* startDepolyment(char* _selectedLocation, char* _serverName);

// cancelDepolyment cancels the deployment for the private server.
//
extern char* cancelDepolyment(void);

// addServerManagerInstance adds a server manager instance manually.
//
extern char* addServerManagerInstance(char* _ip, char* _port, char* _accessToken, char* _tag);

// inviteToServerManagerInstance invites to the server manager instance.
//
extern char* inviteToServerManagerInstance(char* _ip, char* _port, char* _accessToken, char* _inviteName);

// revokeServerManagerInvite revokes the server manager invite.
//
extern char* revokeServerManagerInvite(char* _ip, char* _port, char* _accessToken, char* _inviteName);

// addServerBasedOnURLs adds a server based on the provided URLs.
//
extern char* addServerBasedOnURLs(char* _urls, int _skipCertVerification, char* _serverName);
extern char* setBlockAdsEnabled(int enabled);
extern int isBlockAdsEnabled(void);
extern char* setSmartRoutingEnabled(int enabled);
extern int isSmartRoutingEnabled(void);
extern void registerPlatformCallbacks(OpenTunCallback openTun, ClearDNSCacheCallback clearDNSCache, WriteLogCallback writeLog, RestartServiceCallback restartService, PostServiceCloseCallback postServiceClose, UsePlatformAutoDetectControlCallback usePlatformAutoDetectControl, ReadWIFIStateCallback readWIFIState, UnderNetworkExtensionCallback underNetworkExtension, IncludeAllNetworksCallback includeAllNetworks);
extern void registerSwiftEventCallback(SwiftEventCallback callback);

// startVPNWithPlatform starts the VPN using the registered platform callbacks
//
extern char* startVPNWithPlatform(char* _logDir, char* _dataDir, char* _locale);

// connectToServerWithPlatform connects to a server using the registered platform callbacks
//
extern char* connectToServerWithPlatform(char* _location, char* _tag, char* _logDir, char* _dataDir, char* _locale);

#ifdef __cplusplus
}
#endif
