#!/usr/bin/env perl

use strict;
use warnings;

my $passed = 0;
while (<STDIN>) {
    chomp;
    if (m/^=== (\S+)/) {
        print "$passed passed\n---\n";
        print "$_\n";
        my $test = "data/test/suite/$1.js";
        print "$test\n";
        unlink ".failing";
        symlink $test, ".failing";
        exit 64;
    } elsif (m/passed|as expected$/) {
        $passed += 1
    }
}

print "$passed passed!\n";
