#!/usr/bin/env perl

use strict;
use warnings;

$| = 1;

my $passed = 0;
while (<STDIN>) {
    chomp;
    if (m/^=== (\S+)/) {
        print "$passed passed\n---\n";
        print "$_\n";
        my $test = "data/test/suite/$1.js";
        print "$test\n";
        unlink ".fail";
        symlink $test, ".fail";
        exit 64;
    } elsif (m/passed|as expected$/) {
        $passed += 1;
        print "$_\n";
    }
}

print "$passed passed!\n";
