#!/bin/bash

rm -rf data/test/suite

for test in `grep passed v8 | awk '{ print $1 }'`
do
    mkdir -p `dirname data/test/suite/$test`
    cp data/test/suite.base/$test.js data/test/suite/$test.js
done
