#!/bin/bash

if [ ! -d data/test/suite.base ]
then
    echo "Can't uncull because \"./data/test/suite.base\" is missing"
    exit 64
fi

rm -rf data/test/suite
mv data/test/suite.base data/test/suite
