(function(e){if(!Modernizr.genericDOM){var h=document,k,g,j=/<([\w:]+)/,s={option:1,optgroup:1,legend:1,thead:1,tr:1,td:1,col:1,area:1};e.webshims.fixHTML5=function(e){if("string"!=typeof e||s[(j.exec(e)||["",""])[1].toLowerCase()])return e;if(!g){k=h.body;if(!k)return e;g=h.createElement("div");g.style.display="none"}var i=g.cloneNode(!1);k.appendChild(i);i.innerHTML=e;k.removeChild(i);return i.childNodes}}})(jQuery);
jQuery.webshims.register("dom-extend",function(e,h,k,g,j){var s=h.modules,t=/\s*,\s*/,i={},u={},l={},A={},n={},y=e.fn.val,B=function(b,a,c,d,f){return f?y.call(e(b)):y.call(e(b),c)};e.fn.val=function(b){var a=this[0];arguments.length&&null==b&&(b="");if(!arguments.length)return!a||1!==a.nodeType?y.call(this):e.prop(a,"value",b,"val",!0);if(e.isArray(b))return y.apply(this,arguments);var c=e.isFunction(b);return this.each(function(d){a=this;1===a.nodeType&&(c?(d=b.call(a,d,e.prop(a,"value",j,"val",
!0)),null==d&&(d=""),e.prop(a,"value",d,"val")):e.prop(a,"value",b,"val"))})};var o="_webshimsLib"+Math.round(1E3*Math.random()),x=function(b,a,c){b=b.jquery?b[0]:b;if(!b)return c||{};var d=e.data(b,o);c!==j&&(d||(d=e.data(b,o,{})),a&&(d[a]=c));return a?d&&d[a]:d};[{name:"getNativeElement",prop:"nativeElement"},{name:"getShadowElement",prop:"shadowElement"},{name:"getShadowFocusElement",prop:"shadowFocusElement"}].forEach(function(b){e.fn[b.name]=function(){return this.map(function(){var a=x(this,
"shadowData");return a&&a[b.prop]||this})}});["removeAttr","prop","attr"].forEach(function(b){i[b]=e[b];e[b]=function(a,c,d,f,v){var p="val"==f,h=!p?i[b]:B;if(!a||!u[c]||1!==a.nodeType||!p&&f&&"attr"==b&&e.attrFn[c])return h(a,c,d,f,v);var q=(a.nodeName||"").toLowerCase(),r=l[q],w="attr"==b&&(!1===d||null===d)?"removeAttr":b,g,m,k;r||(r=l["*"]);r&&(r=r[c]);r&&(g=r[w]);if(g){if("value"==c)m=g.isVal,g.isVal=p;if("removeAttr"===w)return g.value.call(a);if(d===j)return g.get?g.get.call(a):g.value;g.set&&
("attr"==b&&!0===d&&(d=c),k=g.set.call(a,d));if("value"==c)g.isVal=m}else k=h(a,c,d,f,v);if((d!==j||"removeAttr"===w)&&n[q]&&n[q][c]){var s;s="removeAttr"==w?!1:"prop"==w?!!d:!0;n[q][c].forEach(function(c){if(!c.only||(c.only="prop"==b)||"attr"==c.only&&"prop"!=b)c.call(a,d,s,p?"val":w,b)})}return k};A[b]=function(a,c,d){l[a]||(l[a]={});l[a][c]||(l[a][c]={});var f=l[a][c][b],v=function(a,f,q){return f&&f[a]?f[a]:q&&q[a]?q[a]:"prop"==b&&"value"==c?function(a){return d.isVal?B(this,c,a,!1,0===arguments.length):
i[b](this,c,a)}:"prop"==b&&"value"==a&&d.value.apply?function(a){var d=i[b](this,c);d&&d.apply&&(d=d.apply(this,arguments));return d}:function(a){return i[b](this,c,a)}};l[a][c][b]=d;if(d.value===j){if(!d.set)d.set=d.writeable?v("set",d,f):h.cfg.useStrict&&"prop"==c?function(){throw c+" is readonly on "+a;}:e.noop;if(!d.get)d.get=v("get",d,f)}["value","get","set"].forEach(function(a){d[a]&&(d["_sup"+a]=v(a,f))})}});var C=!e.browser.msie||8<parseInt(e.browser.version,10),D=function(){var b=h.getPrototypeOf(g.createElement("foobar")),
a=Object.prototype.hasOwnProperty;return function(c,d,f){var e=g.createElement(c),p=h.getPrototypeOf(e);if(C&&p&&b!==p&&(!e[d]||!a.call(e,d))){var i=e[d];f._supvalue=function(){return i&&i.apply?i.apply(this,arguments):i};p[d]=f.value}else f._supvalue=function(){var a=x(this,"propValue");return a&&a[d]&&a[d].apply?a[d].apply(this,arguments):a&&a[d]},m.extendValue(c,d,f.value);f.value._supvalue=f._supvalue}}(),m=function(){var b={};h.addReady(function(a,c){var d={},g=function(b){d[b]||(d[b]=e(a.getElementsByTagName(b)),
c[0]&&e.nodeName(c[0],b)&&(d[b]=d[b].add(c)))};e.each(b,function(a,c){g(a);!c||!c.forEach?h.warn("Error: with "+a+"-property. methods: "+c):c.forEach(function(c){d[a].each(c)})});d=null});var a,c=e([]),d=function(c,d){b[c]?b[c].push(d):b[c]=[d];e.isDOMReady&&(a||e(g.getElementsByTagName(c))).each(d)};return{createTmpCache:function(b){e.isDOMReady&&(a=a||e(g.getElementsByTagName(b)));return a||c},flushTmpCache:function(){a=null},content:function(a,c){d(a,function(){var a=e.attr(this,c);null!=a&&e.attr(this,
c,a)})},createElement:function(a,c){d(a,c)},extendValue:function(a,c,b){d(a,function(){e(this).each(function(){x(this,"propValue",{})[c]=this[c];this[c]=b})})}}}(),z=function(b,a){if(b.defaultValue===j)b.defaultValue="";if(!b.removeAttr)b.removeAttr={value:function(){b[a||"prop"].set.call(this,b.defaultValue);b.removeAttr._supvalue.call(this)}}};e.extend(h,{getID:function(){var b=(new Date).getTime();return function(a){var a=e(a),c=a.attr("id");c||(b++,c="ID-"+b,a.attr("id",c));return c}}(),extendUNDEFProp:function(b,
a){e.each(a,function(a,d){a in b||(b[a]=d)})},createPropDefault:z,data:x,moveToFirstEvent:function(){var b=e._data?"_data":"data";return function(a,c,d){if((a=(e[b](a,"events")||{})[c])&&1<a.length)c=a.pop(),d||(d="bind"),"bind"==d&&a.delegateCount?a.splice(a.delegateCount,0,c):a.unshift(c)}}(),addShadowDom:function(b,a,c){c=c||{};b.jquery&&(b=b[0]);a.jquery&&(a=a[0]);if(!c.shadowFocusElement)c.shadowFocusElement=a;var d=e.data(b,o)||e.data(b,o,{}),f=e.data(a,o)||e.data(a,o,{});d.hasShadow=a;f.nativeElement=
b;f.shadowData=d.shadowData={nativeElement:b,shadowElement:a,shadowFocusElement:c.shadowFocusElement};c.shadowChilds&&c.shadowChilds.each(function(){x(this,"shadowData",f.shadowData)});if(c.data)d.shadowData.data=c.data,f.shadowData.data=c.data;c=null},propTypes:{standard:function(b){z(b);if(!b.prop)b.prop={set:function(a){b.attr.set.call(this,""+a)},get:function(){return b.attr.get.call(this)||b.defaultValue}}},"boolean":function(b){z(b);if(!b.prop)b.prop={set:function(a){a?b.attr.set.call(this,
""):b.removeAttr.value.call(this)},get:function(){return null!=b.attr.get.call(this)}}}},reflectProperties:function(b,a){"string"==typeof a&&(a=a.split(t));a.forEach(function(a){h.defineNodeNamesProperty(b,a,{prop:{set:function(b){e.attr(this,a,b)},get:function(){return e.attr(this,a)||""}}})})},defineNodeNameProperty:function(b,a,c){u[a]=!0;if(c.reflect)h.propTypes[c.propType||"standard"](c);["prop","attr","removeAttr"].forEach(function(d){var f=c[d];f&&(f="prop"===d?e.extend({writeable:!0},f):e.extend({},
f,{writeable:!0}),A[d](b,a,f),"*"!=b&&h.cfg.extendNative&&"prop"==d&&f.value&&e.isFunction(f.value)&&D(b,a,f),c[d]=f)});c.initAttr&&m.content(b,a);return c},defineNodeNameProperties:function(b,a,c,d){for(var e in a)!d&&a[e].initAttr&&m.createTmpCache(b),c&&(a[e][c]?h.log("override: "+b+"["+e+"] for "+c):(a[e][c]={},["value","set","get"].forEach(function(b){b in a[e]&&(a[e][c][b]=a[e][b],delete a[e][b])}))),a[e]=h.defineNodeNameProperty(b,e,a[e]);d||m.flushTmpCache();return a},createElement:function(b,
a,c){var d;e.isFunction(a)&&(a={after:a});m.createTmpCache(b);a.before&&m.createElement(b,a.before);c&&(d=h.defineNodeNameProperties(b,c,!1,!0));a.after&&m.createElement(b,a.after);m.flushTmpCache();return d},onNodeNamesPropertyModify:function(b,a,c,d){"string"==typeof b&&(b=b.split(t));e.isFunction(c)&&(c={set:c});b.forEach(function(b){n[b]||(n[b]={});"string"==typeof a&&(a=a.split(t));c.initAttr&&m.createTmpCache(b);a.forEach(function(a){n[b][a]||(n[b][a]=[],u[a]=!0);if(c.set){if(d)c.set.only=d;
n[b][a].push(c.set)}c.initAttr&&m.content(b,a)});m.flushTmpCache()})},defineNodeNamesBooleanProperty:function(b,a,c){c||(c={});if(e.isFunction(c))c.set=c;h.defineNodeNamesProperty(b,a,{attr:{set:function(b){this.setAttribute(a,b);c.set&&c.set.call(this,!0)},get:function(){return null==this.getAttribute(a)?j:a}},removeAttr:{value:function(){this.removeAttribute(a);c.set&&c.set.call(this,!1)}},reflect:!0,propType:"boolean",initAttr:c.initAttr||!1})},contentAttr:function(b,a,c){if(b.nodeName){if(c===
j)return c=(b.attributes[a]||{}).value,null==c?j:c;"boolean"==typeof c?c?b.setAttribute(a,a):b.removeAttribute(a):b.setAttribute(a,c)}},activeLang:function(){var b=[],a={},c,d,f=/:\/\/|^\.*\//,g=function(a,c,b){return c&&b&&-1!==e.inArray(c,b.availabeLangs||[])?(a.loading=!0,b=b.langSrc,f.test(b)||(b=h.cfg.basePath+b),h.loader.loadScript(b+c+".js",function(){a.langObj[c]?(a.loading=!1,j(a,!0)):e(function(){a.langObj[c]&&j(a,!0);a.loading=!1})}),!0):!1},i=function(b){a[b]&&a[b].forEach(function(a){a.callback()})},
j=function(a,b){if(a.activeLang!=c&&a.activeLang!==d){var e=s[a.module].options;if(a.langObj[c]||d&&a.langObj[d])a.activeLang=c,a.callback(a.langObj[c]||a.langObj[d],c),i(a.module);else if(!b&&!g(a,c,e)&&!g(a,d,e)&&a.langObj[""]&&""!==a.activeLang)a.activeLang="",a.callback(a.langObj[""],c),i(a.module)}};return function(f){if("string"==typeof f&&f!==c)c=f,d=c.split("-")[0],c==d&&(d=!1),e.each(b,function(a,b){j(b)});else if("object"==typeof f)if(f.register)a[f.register]||(a[f.register]=[]),a[f.register].push(f),
f.callback();else{if(!f.activeLang)f.activeLang="";b.push(f);j(f)}return c}}()});e.each({defineNodeNamesProperty:"defineNodeNameProperty",defineNodeNamesProperties:"defineNodeNameProperties",createElements:"createElement"},function(b,a){h[b]=function(b,d,e,g){"string"==typeof b&&(b=b.split(t));var i={};b.forEach(function(b){i[b]=h[a](b,d,e,g)});return i}});h.isReady("webshimLocalization",!0)});
(function(e,h){var k=e.webshims.browserVersion;if(!(e.browser.mozilla&&5<k)&&(!e.browser.msie||12>k&&7<k)){var g={article:"article",aside:"complementary",section:"region",nav:"navigation",address:"contentinfo"},j=function(e,g){e.getAttribute("role")||e.setAttribute("role",g)};e.webshims.addReady(function(k,t){e.each(g,function(g,h){for(var i=e(g,k).add(t.filter(g)),l=0,o=i.length;l<o;l++)j(i[l],h)});if(k===h){var i=h.getElementsByTagName("header")[0],u=h.getElementsByTagName("footer"),l=u.length;
i&&!e(i).closest("section, article")[0]&&j(i,"banner");l&&(i=u[l-1],e(i).closest("section, article")[0]||j(i,"contentinfo"))}})}})(jQuery,document);
