language: go
script: make testall
sudo: false
go:
  - 1.5
  - 1.4
  - 1.3
  - 1.2
install:
  - go get github.com/onsi/ginkgo github.com/onsi/gomega
  - mkdir -p $GOPATH/src/gopkg.in/bsm
  - mv $GOPATH/src/github.com/bsm/ratelimit $GOPATH/src/gopkg.in/bsm/ratelimit.v1
  - cd $GOPATH/src/gopkg.in/bsm/ratelimit.v1
