name: "Pull from transifex"

on:
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pull-strings-from-transifex:
    name: pull-strings-from-transifex
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.CI_PRIVATE_REPOS_GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Checkout
        uses: actions/checkout@v4

      - name: "Pull translations file"
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_PULL_TOKEN }}
          args: --verbose pull

      - name: "Update translations"
        run: |
          set -euo pipefail
          git config user.name git
          git config user.email github-actions@github.com
          git add assets/locales/*.po

          if git diff --cached --quiet; then
            echo "No translation updates to commit."
            exit 0
          fi

          git commit -m "updated translations..."
          git push origin main
