name: "Push to transifex"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-strings-to-transifex:
    name: push-strings-to-transifex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate PO file
        run: |
          sudo apt-get install -y gettext
          msgfmt --check assets/locales/en.po

      - name: "Push main translations file"
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
          args: push -s
